-- =============================================================================
-- MIGRATION 0017: Barry Itabuna full data (extintores 1-276)
-- Sets tipo_carga + setor for every Barry Itabuna slot. Idempotent.
-- =============================================================================
-- 276 extintores Barry Itabuna (1-276)
UPDATE extintores SET tipo_carga='BC 6kg', setor='portaria' WHERE regiao='Barry Itabuna' AND numero_int=1;
UPDATE extintores SET tipo_carga='AP', setor='portaria' WHERE regiao='Barry Itabuna' AND numero_int=2;
UPDATE extintores SET tipo_carga='BC 6kg', setor='portaria' WHERE regiao='Barry Itabuna' AND numero_int=3;
UPDATE extintores SET tipo_carga='CO2', setor='entrada do laboratório microbiologia' WHERE regiao='Barry Itabuna' AND numero_int=4;
UPDATE extintores SET tipo_carga='AP', setor='entrada do laboratório microbiologia' WHERE regiao='Barry Itabuna' AND numero_int=5;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='corredor do laboratório' WHERE regiao='Barry Itabuna' AND numero_int=6;
UPDATE extintores SET tipo_carga='ABC 4kg', setor='laboratório' WHERE regiao='Barry Itabuna' AND numero_int=7;
UPDATE extintores SET tipo_carga='CO2', setor='laboratório' WHERE regiao='Barry Itabuna' AND numero_int=8;
UPDATE extintores SET tipo_carga='CO2', setor='laboratório' WHERE regiao='Barry Itabuna' AND numero_int=9;
UPDATE extintores SET tipo_carga='CO2 4kg', setor='patógeno' WHERE regiao='Barry Itabuna' AND numero_int=10;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='patógeno' WHERE regiao='Barry Itabuna' AND numero_int=11;
UPDATE extintores SET tipo_carga='BC 6kg', setor='corredor ADM' WHERE regiao='Barry Itabuna' AND numero_int=12;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='ADM' WHERE regiao='Barry Itabuna' AND numero_int=13;
UPDATE extintores SET tipo_carga='CO2', setor='ADM' WHERE regiao='Barry Itabuna' AND numero_int=14;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='garagem' WHERE regiao='Barry Itabuna' AND numero_int=15;
UPDATE extintores SET tipo_carga='ABC 4kg', setor='fundo do ADM' WHERE regiao='Barry Itabuna' AND numero_int=16;
UPDATE extintores SET tipo_carga='CO2', setor='fundo laboratório microbiologia área externa' WHERE regiao='Barry Itabuna' AND numero_int=17;
UPDATE extintores SET tipo_carga='CO2', setor='fundo laboratório microbiologia área externa' WHERE regiao='Barry Itabuna' AND numero_int=18;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='área externa em frente a subestação' WHERE regiao='Barry Itabuna' AND numero_int=19;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='' WHERE regiao='Barry Itabuna' AND numero_int=20;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='próximo casa de gás natural' WHERE regiao='Barry Itabuna' AND numero_int=21;
UPDATE extintores SET tipo_carga='ABC 12kg', setor='área externa GLP' WHERE regiao='Barry Itabuna' AND numero_int=22;
UPDATE extintores SET tipo_carga='BC 6kg', setor='área externa escritório armazém de favas' WHERE regiao='Barry Itabuna' AND numero_int=23;
UPDATE extintores SET tipo_carga='AP', setor='área externa escritório armazém de favas' WHERE regiao='Barry Itabuna' AND numero_int=24;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='área externa GLP' WHERE regiao='Barry Itabuna' AND numero_int=25;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='fundo da caldeira' WHERE regiao='Barry Itabuna' AND numero_int=26;
UPDATE extintores SET tipo_carga='CO2', setor='derretedor' WHERE regiao='Barry Itabuna' AND numero_int=27;
UPDATE extintores SET tipo_carga='BC 12kg', setor='derretedor' WHERE regiao='Barry Itabuna' AND numero_int=28;
UPDATE extintores SET tipo_carga='AP', setor='derretedor' WHERE regiao='Barry Itabuna' AND numero_int=29;
UPDATE extintores SET tipo_carga='AP', setor='derretedor' WHERE regiao='Barry Itabuna' AND numero_int=30;
UPDATE extintores SET tipo_carga='AP', setor='derretedor' WHERE regiao='Barry Itabuna' AND numero_int=31;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='área externa fundo utilidades' WHERE regiao='Barry Itabuna' AND numero_int=32;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='utilidades' WHERE regiao='Barry Itabuna' AND numero_int=33;
UPDATE extintores SET tipo_carga='CO2', setor='utilidades' WHERE regiao='Barry Itabuna' AND numero_int=34;
UPDATE extintores SET tipo_carga='CO2', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=35;
UPDATE extintores SET tipo_carga='AP', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=36;
UPDATE extintores SET tipo_carga='AP', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=37;
UPDATE extintores SET tipo_carga='AP', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=38;
UPDATE extintores SET tipo_carga='AP', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=39;
UPDATE extintores SET tipo_carga='AP', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=40;
UPDATE extintores SET tipo_carga='AP', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=41;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=42;
UPDATE extintores SET tipo_carga='ABC 4kg', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=43;
UPDATE extintores SET tipo_carga='AP', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=44;
UPDATE extintores SET tipo_carga='CO2', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=45;
UPDATE extintores SET tipo_carga='AP', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=46;
UPDATE extintores SET tipo_carga='CO2', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=47;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=48;
UPDATE extintores SET tipo_carga='AP', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=49;
UPDATE extintores SET tipo_carga='ABC 4kg', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=50;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=51;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=52;
UPDATE extintores SET tipo_carga='AP', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=53;
UPDATE extintores SET tipo_carga='AP', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=54;
UPDATE extintores SET tipo_carga='AP', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=55;
UPDATE extintores SET tipo_carga='AP', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=56;
UPDATE extintores SET tipo_carga='AP', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=57;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='favas' WHERE regiao='Barry Itabuna' AND numero_int=58;
UPDATE extintores SET tipo_carga='AP', setor='favas - 1 andar' WHERE regiao='Barry Itabuna' AND numero_int=59;
UPDATE extintores SET tipo_carga='CO2', setor='favas -1 andar' WHERE regiao='Barry Itabuna' AND numero_int=60;
UPDATE extintores SET tipo_carga='AP', setor='favas - 2 andar' WHERE regiao='Barry Itabuna' AND numero_int=61;
UPDATE extintores SET tipo_carga='CO2', setor='favas -2 andar' WHERE regiao='Barry Itabuna' AND numero_int=62;
UPDATE extintores SET tipo_carga='CO2', setor='sala de comando' WHERE regiao='Barry Itabuna' AND numero_int=63;
UPDATE extintores SET tipo_carga='BC 6kg', setor='sala de comando' WHERE regiao='Barry Itabuna' AND numero_int=64;
UPDATE extintores SET tipo_carga='AP', setor='seleção linha 2 infrared' WHERE regiao='Barry Itabuna' AND numero_int=65;
UPDATE extintores SET tipo_carga='AP', setor='seleção linha 2 infrared' WHERE regiao='Barry Itabuna' AND numero_int=66;
UPDATE extintores SET tipo_carga='BC 6kg', setor='seleção linha 2 infrared' WHERE regiao='Barry Itabuna' AND numero_int=67;
UPDATE extintores SET tipo_carga='CO2', setor='seleção linha 2 infrared' WHERE regiao='Barry Itabuna' AND numero_int=68;
UPDATE extintores SET tipo_carga='BC 6kg', setor='separação linda 2 piso amarelo' WHERE regiao='Barry Itabuna' AND numero_int=69;
UPDATE extintores SET tipo_carga='CO2', setor='separação linda 2 piso amarelo' WHERE regiao='Barry Itabuna' AND numero_int=70;
UPDATE extintores SET tipo_carga='BC 6kg', setor='separação linda 2 piso amarelo' WHERE regiao='Barry Itabuna' AND numero_int=71;
UPDATE extintores SET tipo_carga='BC 6kg', setor='separação cascas cacau' WHERE regiao='Barry Itabuna' AND numero_int=72;
UPDATE extintores SET tipo_carga='CO2', setor='separação cascas cacau' WHERE regiao='Barry Itabuna' AND numero_int=73;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='separação cascas cacau' WHERE regiao='Barry Itabuna' AND numero_int=74;
UPDATE extintores SET tipo_carga='CO2', setor='separação cascas cacau' WHERE regiao='Barry Itabuna' AND numero_int=75;
UPDATE extintores SET tipo_carga='CO2', setor='separação cascas cacau' WHERE regiao='Barry Itabuna' AND numero_int=76;
UPDATE extintores SET tipo_carga='ABC 4kg', setor='separação cascas cacau' WHERE regiao='Barry Itabuna' AND numero_int=77;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='torrefação' WHERE regiao='Barry Itabuna' AND numero_int=78;
UPDATE extintores SET tipo_carga='CO2', setor='torrefação' WHERE regiao='Barry Itabuna' AND numero_int=79;
UPDATE extintores SET tipo_carga='CO2', setor='sala supervisão' WHERE regiao='Barry Itabuna' AND numero_int=80;
UPDATE extintores SET tipo_carga='CO2', setor='sala supervisão' WHERE regiao='Barry Itabuna' AND numero_int=81;
UPDATE extintores SET tipo_carga='CO2', setor='substação' WHERE regiao='Barry Itabuna' AND numero_int=82;
UPDATE extintores SET tipo_carga='CO2', setor='substação' WHERE regiao='Barry Itabuna' AND numero_int=83;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='perto da central' WHERE regiao='Barry Itabuna' AND numero_int=84;
UPDATE extintores SET tipo_carga='CO2', setor='entrada da fábrica' WHERE regiao='Barry Itabuna' AND numero_int=85;
UPDATE extintores SET tipo_carga='CO2', setor='substação térreo' WHERE regiao='Barry Itabuna' AND numero_int=86;
UPDATE extintores SET tipo_carga='CO2', setor='área externa circulação fábrica' WHERE regiao='Barry Itabuna' AND numero_int=87;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='circulação fábrica' WHERE regiao='Barry Itabuna' AND numero_int=88;
UPDATE extintores SET tipo_carga='BC 6kg', setor='circulação fábrica' WHERE regiao='Barry Itabuna' AND numero_int=89;
UPDATE extintores SET tipo_carga='CO2', setor='oficina' WHERE regiao='Barry Itabuna' AND numero_int=90;
UPDATE extintores SET tipo_carga='ABC 4kg', setor='utilidades linha 1' WHERE regiao='Barry Itabuna' AND numero_int=91;
UPDATE extintores SET tipo_carga='CO2', setor='almoxarifado' WHERE regiao='Barry Itabuna' AND numero_int=92;
UPDATE extintores SET tipo_carga='BC 6kg', setor='almoxarifado' WHERE regiao='Barry Itabuna' AND numero_int=93;
UPDATE extintores SET tipo_carga='AP', setor='almoxarifado' WHERE regiao='Barry Itabuna' AND numero_int=94;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='área externa almoxarifado' WHERE regiao='Barry Itabuna' AND numero_int=95;
UPDATE extintores SET tipo_carga='BC', setor='área externa almoxarifado' WHERE regiao='Barry Itabuna' AND numero_int=96;
UPDATE extintores SET tipo_carga='AP', setor='área externa almoxarifado' WHERE regiao='Barry Itabuna' AND numero_int=97;
UPDATE extintores SET tipo_carga='ABC 12kg', setor='área externa GLP' WHERE regiao='Barry Itabuna' AND numero_int=98;
UPDATE extintores SET tipo_carga='CO2', setor='produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=99;
UPDATE extintores SET tipo_carga='ABC 4kg', setor='produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=100;
UPDATE extintores SET tipo_carga='CO2', setor='produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=101;
UPDATE extintores SET tipo_carga='CO2', setor='produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=102;
UPDATE extintores SET tipo_carga='AP', setor='produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=103;
UPDATE extintores SET tipo_carga='AP', setor='produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=104;
UPDATE extintores SET tipo_carga='CO2', setor='produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=105;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=106;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=107;
UPDATE extintores SET tipo_carga='AP', setor='produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=108;
UPDATE extintores SET tipo_carga='BC', setor='área circulação fábrica' WHERE regiao='Barry Itabuna' AND numero_int=109;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='circulação fábrica' WHERE regiao='Barry Itabuna' AND numero_int=110;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='área externa GLP' WHERE regiao='Barry Itabuna' AND numero_int=111;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='área externa lavatório' WHERE regiao='Barry Itabuna' AND numero_int=112;
UPDATE extintores SET tipo_carga='BC 6kg', setor='área externa lavatório' WHERE regiao='Barry Itabuna' AND numero_int=113;
UPDATE extintores SET tipo_carga='BC 6kg', setor='área externa plásticos' WHERE regiao='Barry Itabuna' AND numero_int=114;
UPDATE extintores SET tipo_carga='CO2', setor='área externa GLP' WHERE regiao='Barry Itabuna' AND numero_int=115;
UPDATE extintores SET tipo_carga='CO2', setor='área externa fundo da brigada' WHERE regiao='Barry Itabuna' AND numero_int=116;
UPDATE extintores SET tipo_carga='AP', setor='área externa HSE' WHERE regiao='Barry Itabuna' AND numero_int=117;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='área externa HSE' WHERE regiao='Barry Itabuna' AND numero_int=118;
UPDATE extintores SET tipo_carga='ABC 12kg', setor='área externa HSE' WHERE regiao='Barry Itabuna' AND numero_int=119;
UPDATE extintores SET tipo_carga='ABC 8kg', setor='casa de bombas' WHERE regiao='Barry Itabuna' AND numero_int=120;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='área painel elétrico do silos' WHERE regiao='Barry Itabuna' AND numero_int=121;
UPDATE extintores SET tipo_carga='CO2', setor='moinho área branca' WHERE regiao='Barry Itabuna' AND numero_int=122;
UPDATE extintores SET tipo_carga='CO2', setor='prensa área branca' WHERE regiao='Barry Itabuna' AND numero_int=123;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='prensa área branca' WHERE regiao='Barry Itabuna' AND numero_int=124;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='moagem linha 2' WHERE regiao='Barry Itabuna' AND numero_int=125;
UPDATE extintores SET tipo_carga='AP', setor='moagem linha 2' WHERE regiao='Barry Itabuna' AND numero_int=126;
UPDATE extintores SET tipo_carga='BC 6kg', setor='moagem linha 2' WHERE regiao='Barry Itabuna' AND numero_int=127;
UPDATE extintores SET tipo_carga='CO2', setor='moagem linha 2' WHERE regiao='Barry Itabuna' AND numero_int=128;
UPDATE extintores SET tipo_carga='CO2', setor='moagem linha 2' WHERE regiao='Barry Itabuna' AND numero_int=129;
UPDATE extintores SET tipo_carga='BC 6kg', setor='moagem linha 2' WHERE regiao='Barry Itabuna' AND numero_int=130;
UPDATE extintores SET tipo_carga='CO2', setor='torrefação linha 2' WHERE regiao='Barry Itabuna' AND numero_int=131;
UPDATE extintores SET tipo_carga='CO2', setor='torrefação linha 2' WHERE regiao='Barry Itabuna' AND numero_int=132;
UPDATE extintores SET tipo_carga='CO2', setor='torrefação linha 2 -1 andar' WHERE regiao='Barry Itabuna' AND numero_int=133;
UPDATE extintores SET tipo_carga='CO2', setor='torrefação linha 2' WHERE regiao='Barry Itabuna' AND numero_int=134;
UPDATE extintores SET tipo_carga='AP', setor='silo dos GDS' WHERE regiao='Barry Itabuna' AND numero_int=135;
UPDATE extintores SET tipo_carga='CO2', setor='torrefação linha 2 - 3 andar' WHERE regiao='Barry Itabuna' AND numero_int=136;
UPDATE extintores SET tipo_carga='AP', setor='torrefação linha 2 - 4 andar' WHERE regiao='Barry Itabuna' AND numero_int=137;
UPDATE extintores SET tipo_carga='AP', setor='torrefação linha 2 - 5 andar' WHERE regiao='Barry Itabuna' AND numero_int=138;
UPDATE extintores SET tipo_carga='AP', setor='corredor do laboratório' WHERE regiao='Barry Itabuna' AND numero_int=139;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='laboratório da fábrica' WHERE regiao='Barry Itabuna' AND numero_int=140;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='laboratório da fábrica' WHERE regiao='Barry Itabuna' AND numero_int=141;
UPDATE extintores SET tipo_carga='AP', setor='laboratório da fábrica' WHERE regiao='Barry Itabuna' AND numero_int=142;
UPDATE extintores SET tipo_carga='CO2', setor='laboratório da fábrica' WHERE regiao='Barry Itabuna' AND numero_int=143;
UPDATE extintores SET tipo_carga='', setor='laboratório da fábrica' WHERE regiao='Barry Itabuna' AND numero_int=144;
UPDATE extintores SET tipo_carga='AP', setor='ADM laboratório' WHERE regiao='Barry Itabuna' AND numero_int=145;
UPDATE extintores SET tipo_carga='AP', setor='ADM laboratório' WHERE regiao='Barry Itabuna' AND numero_int=146;
UPDATE extintores SET tipo_carga='CO2', setor='ADM laboratório' WHERE regiao='Barry Itabuna' AND numero_int=147;
UPDATE extintores SET tipo_carga='CO2', setor='prensas 3' WHERE regiao='Barry Itabuna' AND numero_int=148;
UPDATE extintores SET tipo_carga='CO2', setor='prensas 3' WHERE regiao='Barry Itabuna' AND numero_int=149;
UPDATE extintores SET tipo_carga='CO2', setor='prensas 4' WHERE regiao='Barry Itabuna' AND numero_int=150;
UPDATE extintores SET tipo_carga='CO2', setor='prensas 4' WHERE regiao='Barry Itabuna' AND numero_int=151;
UPDATE extintores SET tipo_carga='CO2', setor='prensas 3' WHERE regiao='Barry Itabuna' AND numero_int=152;
UPDATE extintores SET tipo_carga='CO2', setor='sala de painéis das prensas' WHERE regiao='Barry Itabuna' AND numero_int=153;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='embalagem fibra de manteiga' WHERE regiao='Barry Itabuna' AND numero_int=154;
UPDATE extintores SET tipo_carga='BC 6kg', setor='embalagem de manteiga' WHERE regiao='Barry Itabuna' AND numero_int=155;
UPDATE extintores SET tipo_carga='CO2', setor='pulverização linha 2' WHERE regiao='Barry Itabuna' AND numero_int=156;
UPDATE extintores SET tipo_carga='AP', setor='pulverização linha 2' WHERE regiao='Barry Itabuna' AND numero_int=157;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='pulverização linha 2' WHERE regiao='Barry Itabuna' AND numero_int=158;
UPDATE extintores SET tipo_carga='AP', setor='pulverização linha 1' WHERE regiao='Barry Itabuna' AND numero_int=159;
UPDATE extintores SET tipo_carga='BC 6kg', setor='pulverização linha 1' WHERE regiao='Barry Itabuna' AND numero_int=160;
UPDATE extintores SET tipo_carga='AP', setor='pulverização linha 1' WHERE regiao='Barry Itabuna' AND numero_int=161;
UPDATE extintores SET tipo_carga='AP', setor='pulverização linha 1' WHERE regiao='Barry Itabuna' AND numero_int=162;
UPDATE extintores SET tipo_carga='AP', setor='pulverização linha 1' WHERE regiao='Barry Itabuna' AND numero_int=163;
UPDATE extintores SET tipo_carga='AP', setor='pulverização linha 1' WHERE regiao='Barry Itabuna' AND numero_int=164;
UPDATE extintores SET tipo_carga='AP', setor='pulverização linha 1' WHERE regiao='Barry Itabuna' AND numero_int=165;
UPDATE extintores SET tipo_carga='BC 6kg', setor='pulverização linha 1' WHERE regiao='Barry Itabuna' AND numero_int=166;
UPDATE extintores SET tipo_carga='CO2', setor='pulverização linha 2' WHERE regiao='Barry Itabuna' AND numero_int=167;
UPDATE extintores SET tipo_carga='CO2', setor='pulverização linha 2' WHERE regiao='Barry Itabuna' AND numero_int=168;
UPDATE extintores SET tipo_carga='CO2', setor='mix' WHERE regiao='Barry Itabuna' AND numero_int=169;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='mix' WHERE regiao='Barry Itabuna' AND numero_int=170;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='mix' WHERE regiao='Barry Itabuna' AND numero_int=171;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='mix' WHERE regiao='Barry Itabuna' AND numero_int=172;
UPDATE extintores SET tipo_carga='CO2', setor='mix' WHERE regiao='Barry Itabuna' AND numero_int=173;
UPDATE extintores SET tipo_carga='CO2', setor='mix' WHERE regiao='Barry Itabuna' AND numero_int=174;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='sala compressor' WHERE regiao='Barry Itabuna' AND numero_int=175;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='pulverização linha 3' WHERE regiao='Barry Itabuna' AND numero_int=176;
UPDATE extintores SET tipo_carga='ABC 4kg', setor='pulverização linha 3' WHERE regiao='Barry Itabuna' AND numero_int=177;
UPDATE extintores SET tipo_carga='ABC 4kg', setor='pulverização linha 3' WHERE regiao='Barry Itabuna' AND numero_int=178;
UPDATE extintores SET tipo_carga='ABC 4kg', setor='pulverização linha 3' WHERE regiao='Barry Itabuna' AND numero_int=179;
UPDATE extintores SET tipo_carga='ABC 4kg', setor='pulverização linha 3' WHERE regiao='Barry Itabuna' AND numero_int=180;
UPDATE extintores SET tipo_carga='ABC 4kg', setor='pulverização linha 3' WHERE regiao='Barry Itabuna' AND numero_int=181;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='pulverização linha 3' WHERE regiao='Barry Itabuna' AND numero_int=182;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='pulverização linha 3' WHERE regiao='Barry Itabuna' AND numero_int=183;
UPDATE extintores SET tipo_carga='CO2', setor='substação produtos acabados' WHERE regiao='Barry Itabuna' AND numero_int=184;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='substação produtos acabados' WHERE regiao='Barry Itabuna' AND numero_int=185;
UPDATE extintores SET tipo_carga='AP', setor='pulverização linha 3 -1 andar' WHERE regiao='Barry Itabuna' AND numero_int=186;
UPDATE extintores SET tipo_carga='AP', setor='pulverização linha 3 - 2 andar' WHERE regiao='Barry Itabuna' AND numero_int=187;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='pulverização linha 3 -2 andar' WHERE regiao='Barry Itabuna' AND numero_int=188;
UPDATE extintores SET tipo_carga='AP', setor='pulverização linha 3 -2 andar' WHERE regiao='Barry Itabuna' AND numero_int=189;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='pulverização linha 3 -2 andar' WHERE regiao='Barry Itabuna' AND numero_int=190;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='pulverização linha 3 -3 andar' WHERE regiao='Barry Itabuna' AND numero_int=191;
UPDATE extintores SET tipo_carga='AP', setor='área externa resíduos Nestle' WHERE regiao='Barry Itabuna' AND numero_int=192;
UPDATE extintores SET tipo_carga='CO2', setor='área externa resíduos Nestle' WHERE regiao='Barry Itabuna' AND numero_int=193;
UPDATE extintores SET tipo_carga='AP', setor='vestiário terceiros' WHERE regiao='Barry Itabuna' AND numero_int=194;
UPDATE extintores SET tipo_carga='ABC 8kg', setor='vestiário terceiros' WHERE regiao='Barry Itabuna' AND numero_int=195;
UPDATE extintores SET tipo_carga='AP', setor='vestiário terceiros Nestle' WHERE regiao='Barry Itabuna' AND numero_int=196;
UPDATE extintores SET tipo_carga='ABC 8kg', setor='vestiário terceiros Nestle' WHERE regiao='Barry Itabuna' AND numero_int=197;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='próximo estoque GRSA' WHERE regiao='Barry Itabuna' AND numero_int=198;
UPDATE extintores SET tipo_carga='AP', setor='próximo estoque GRSA' WHERE regiao='Barry Itabuna' AND numero_int=199;
UPDATE extintores SET tipo_carga='AP', setor='próximo sala de jogos Nestle' WHERE regiao='Barry Itabuna' AND numero_int=200;
UPDATE extintores SET tipo_carga='AP', setor='entrada do refeitório' WHERE regiao='Barry Itabuna' AND numero_int=201;
UPDATE extintores SET tipo_carga='CO2', setor='entrada do refeitório' WHERE regiao='Barry Itabuna' AND numero_int=202;
UPDATE extintores SET tipo_carga='AP', setor='em frente auditório' WHERE regiao='Barry Itabuna' AND numero_int=203;
UPDATE extintores SET tipo_carga='CO2', setor='em frente auditório' WHERE regiao='Barry Itabuna' AND numero_int=204;
UPDATE extintores SET tipo_carga='CO2', setor='auditório' WHERE regiao='Barry Itabuna' AND numero_int=205;
UPDATE extintores SET tipo_carga='CO2', setor='ADM Nestle' WHERE regiao='Barry Itabuna' AND numero_int=206;
UPDATE extintores SET tipo_carga='CO2', setor='ADM Nestle' WHERE regiao='Barry Itabuna' AND numero_int=207;
UPDATE extintores SET tipo_carga='CO2', setor='ADM Nestle' WHERE regiao='Barry Itabuna' AND numero_int=208;
UPDATE extintores SET tipo_carga='BC 6kg', setor='ADM Nestle' WHERE regiao='Barry Itabuna' AND numero_int=209;
UPDATE extintores SET tipo_carga='CO2', setor='ADM Nestle' WHERE regiao='Barry Itabuna' AND numero_int=210;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='guarita Nestle' WHERE regiao='Barry Itabuna' AND numero_int=211;
UPDATE extintores SET tipo_carga='CO2', setor='substação Nestle' WHERE regiao='Barry Itabuna' AND numero_int=212;
UPDATE extintores SET tipo_carga='AP', setor='sala de comando caldeira biomassa Nestle' WHERE regiao='Barry Itabuna' AND numero_int=213;
UPDATE extintores SET tipo_carga='CO2', setor='sala de comando caldeira biomassa Nestle' WHERE regiao='Barry Itabuna' AND numero_int=214;
UPDATE extintores SET tipo_carga='AP', setor='sala de comando caldeira biomassa Nestle' WHERE regiao='Barry Itabuna' AND numero_int=215;
UPDATE extintores SET tipo_carga='CO2', setor='sala de painéis Nestle' WHERE regiao='Barry Itabuna' AND numero_int=216;
UPDATE extintores SET tipo_carga='AP', setor='próximo sala controle caldeira Nestle' WHERE regiao='Barry Itabuna' AND numero_int=217;
UPDATE extintores SET tipo_carga='AP', setor='próximo sala controle caldeira Nestle' WHERE regiao='Barry Itabuna' AND numero_int=218;
UPDATE extintores SET tipo_carga='AP', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=219;
UPDATE extintores SET tipo_carga='ABC 8kg', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=220;
UPDATE extintores SET tipo_carga='ABC 8kg', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=221;
UPDATE extintores SET tipo_carga='AP', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=222;
UPDATE extintores SET tipo_carga='AP', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=223;
UPDATE extintores SET tipo_carga='ABC 4kg', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=224;
UPDATE extintores SET tipo_carga='AP', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=225;
UPDATE extintores SET tipo_carga='CO2', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=226;
UPDATE extintores SET tipo_carga='AP', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=227;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=228;
UPDATE extintores SET tipo_carga='BC 6kg', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=229;
UPDATE extintores SET tipo_carga='ABC 8kg', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=230;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=231;
UPDATE extintores SET tipo_carga='AP', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=232;
UPDATE extintores SET tipo_carga='AP', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=233;
UPDATE extintores SET tipo_carga='AP', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=234;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=235;
UPDATE extintores SET tipo_carga='AP', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=236;
UPDATE extintores SET tipo_carga='AP', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=237;
UPDATE extintores SET tipo_carga='AP', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=238;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=239;
UPDATE extintores SET tipo_carga='AP', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=240;
UPDATE extintores SET tipo_carga='AP', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=241;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=242;
UPDATE extintores SET tipo_carga='ABC 8kg', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=243;
UPDATE extintores SET tipo_carga='AP', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=244;
UPDATE extintores SET tipo_carga='ABC 8kg', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=245;
UPDATE extintores SET tipo_carga='AP', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=246;
UPDATE extintores SET tipo_carga='AP', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=247;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=248;
UPDATE extintores SET tipo_carga='AP', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=249;
UPDATE extintores SET tipo_carga='CO2', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=250;
UPDATE extintores SET tipo_carga='AP', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=251;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=252;
UPDATE extintores SET tipo_carga='CO2', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=253;
UPDATE extintores SET tipo_carga='BC 6kg', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=254;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=255;
UPDATE extintores SET tipo_carga='CO2', setor='Nestle produto acabado' WHERE regiao='Barry Itabuna' AND numero_int=256;
UPDATE extintores SET tipo_carga='AP', setor='docas Nestle' WHERE regiao='Barry Itabuna' AND numero_int=257;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='docas Nestle' WHERE regiao='Barry Itabuna' AND numero_int=258;
UPDATE extintores SET tipo_carga='BC 6kg', setor='docas Nestle' WHERE regiao='Barry Itabuna' AND numero_int=259;
UPDATE extintores SET tipo_carga='ABC 8kg', setor='docas Nestle' WHERE regiao='Barry Itabuna' AND numero_int=260;
UPDATE extintores SET tipo_carga='AP', setor='área externa fundo Nestle' WHERE regiao='Barry Itabuna' AND numero_int=261;
UPDATE extintores SET tipo_carga='AP', setor='tanque desativado Nestle' WHERE regiao='Barry Itabuna' AND numero_int=262;
UPDATE extintores SET tipo_carga='BC 6kg', setor='tanque desativado Nestle' WHERE regiao='Barry Itabuna' AND numero_int=263;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='tanque desativado Nestle' WHERE regiao='Barry Itabuna' AND numero_int=264;
UPDATE extintores SET tipo_carga='ABC 8kg', setor='tanque desativado Nestle' WHERE regiao='Barry Itabuna' AND numero_int=265;
UPDATE extintores SET tipo_carga='BC 6kg', setor='GLP neste' WHERE regiao='Barry Itabuna' AND numero_int=266;
UPDATE extintores SET tipo_carga='CO2', setor='GLP Nestle' WHERE regiao='Barry Itabuna' AND numero_int=267;
UPDATE extintores SET tipo_carga='CO2', setor='área externa Nestle' WHERE regiao='Barry Itabuna' AND numero_int=268;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='estoque produto químicos Nestle' WHERE regiao='Barry Itabuna' AND numero_int=269;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='material inflamável Nestle' WHERE regiao='Barry Itabuna' AND numero_int=270;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='material inflamável Nestle' WHERE regiao='Barry Itabuna' AND numero_int=271;
UPDATE extintores SET tipo_carga='CO2', setor='sala de tintas Nestle' WHERE regiao='Barry Itabuna' AND numero_int=272;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='refeitório' WHERE regiao='Barry Itabuna' AND numero_int=273;
UPDATE extintores SET tipo_carga='CO2 10kg', setor='carretinha refeitório' WHERE regiao='Barry Itabuna' AND numero_int=274;
UPDATE extintores SET tipo_carga='BC 8kg', setor='sala de ar comprimido' WHERE regiao='Barry Itabuna' AND numero_int=275;
UPDATE extintores SET tipo_carga='CO2', setor='casa de bombas' WHERE regiao='Barry Itabuna' AND numero_int=276;
