-- =============================================================================
-- MIGRATION 0019: Ilhéus data (extintores 1-200; region total is 300)
-- Sets tipo_carga + setor per pre-seeded slot. Idempotent.
-- =============================================================================
-- 200 extintores Ilhéus (1-200)
UPDATE extintores SET tipo_carga='ABC 6kg', setor='ETE' WHERE regiao='Ilhéus' AND numero_int=1;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='ETE' WHERE regiao='Ilhéus' AND numero_int=2;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='ADM' WHERE regiao='Ilhéus' AND numero_int=3;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Recepção ADM' WHERE regiao='Ilhéus' AND numero_int=4;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='ADM' WHERE regiao='Ilhéus' AND numero_int=5;
UPDATE extintores SET tipo_carga='BC 6kg', setor='Recepção ADM' WHERE regiao='Ilhéus' AND numero_int=6;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Garagem fundo ADM' WHERE regiao='Ilhéus' AND numero_int=7;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='CBR' WHERE regiao='Ilhéus' AND numero_int=8;
UPDATE extintores SET tipo_carga='10A80BC 10 4,5kg', setor='CBR' WHERE regiao='Ilhéus' AND numero_int=9;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='CBR' WHERE regiao='Ilhéus' AND numero_int=10;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Sala de sopradores' WHERE regiao='Ilhéus' AND numero_int=11;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Sala de sopradores' WHERE regiao='Ilhéus' AND numero_int=12;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Guarita' WHERE regiao='Ilhéus' AND numero_int=13;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Guarita' WHERE regiao='Ilhéus' AND numero_int=14;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Laboratório' WHERE regiao='Ilhéus' AND numero_int=15;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Entrada HSE' WHERE regiao='Ilhéus' AND numero_int=16;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Entrada HSE' WHERE regiao='Ilhéus' AND numero_int=17;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Em frente med. Ocup' WHERE regiao='Ilhéus' AND numero_int=18;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='RH' WHERE regiao='Ilhéus' AND numero_int=19;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='RH' WHERE regiao='Ilhéus' AND numero_int=20;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Refeitório' WHERE regiao='Ilhéus' AND numero_int=21;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Entrada refeitório' WHERE regiao='Ilhéus' AND numero_int=22;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Cozinha' WHERE regiao='Ilhéus' AND numero_int=23;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Cozinha' WHERE regiao='Ilhéus' AND numero_int=24;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área ext. Cozinha' WHERE regiao='Ilhéus' AND numero_int=25;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área de lazer' WHERE regiao='Ilhéus' AND numero_int=26;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área de lazer' WHERE regiao='Ilhéus' AND numero_int=27;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Em frente banheiro' WHERE regiao='Ilhéus' AND numero_int=28;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Produtos acabados' WHERE regiao='Ilhéus' AND numero_int=29;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Produtos acabados' WHERE regiao='Ilhéus' AND numero_int=30;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Produtos acabados' WHERE regiao='Ilhéus' AND numero_int=31;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área de circulação' WHERE regiao='Ilhéus' AND numero_int=32;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Produtos acabados' WHERE regiao='Ilhéus' AND numero_int=33;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Produtos acabados' WHERE regiao='Ilhéus' AND numero_int=34;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Produtos acabados' WHERE regiao='Ilhéus' AND numero_int=35;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Produtos acabados' WHERE regiao='Ilhéus' AND numero_int=36;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Produtos acabados' WHERE regiao='Ilhéus' AND numero_int=37;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área de circulação' WHERE regiao='Ilhéus' AND numero_int=38;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Produtos acabados' WHERE regiao='Ilhéus' AND numero_int=39;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Produtos acabados' WHERE regiao='Ilhéus' AND numero_int=40;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Produtos acabados' WHERE regiao='Ilhéus' AND numero_int=41;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Produtos acabados' WHERE regiao='Ilhéus' AND numero_int=42;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Produtos acabados' WHERE regiao='Ilhéus' AND numero_int=43;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área de circulação' WHERE regiao='Ilhéus' AND numero_int=44;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Armazém embalagens' WHERE regiao='Ilhéus' AND numero_int=45;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Armazém embalagens' WHERE regiao='Ilhéus' AND numero_int=46;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Armazém embalagens' WHERE regiao='Ilhéus' AND numero_int=47;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área ext. Operações' WHERE regiao='Ilhéus' AND numero_int=48;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área ext. Operações' WHERE regiao='Ilhéus' AND numero_int=49;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Docas' WHERE regiao='Ilhéus' AND numero_int=50;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Moega' WHERE regiao='Ilhéus' AND numero_int=51;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Moega' WHERE regiao='Ilhéus' AND numero_int=52;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Moega' WHERE regiao='Ilhéus' AND numero_int=53;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Moega' WHERE regiao='Ilhéus' AND numero_int=54;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Moega' WHERE regiao='Ilhéus' AND numero_int=55;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Moega' WHERE regiao='Ilhéus' AND numero_int=56;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Docas' WHERE regiao='Ilhéus' AND numero_int=57;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Moega' WHERE regiao='Ilhéus' AND numero_int=58;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Docas e esteiras' WHERE regiao='Ilhéus' AND numero_int=59;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Docas e esteiras' WHERE regiao='Ilhéus' AND numero_int=60;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Docas e esteiras' WHERE regiao='Ilhéus' AND numero_int=61;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área vermelha' WHERE regiao='Ilhéus' AND numero_int=62;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Área vermelha' WHERE regiao='Ilhéus' AND numero_int=63;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área vermelha externa' WHERE regiao='Ilhéus' AND numero_int=64;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Caldeira' WHERE regiao='Ilhéus' AND numero_int=65;
UPDATE extintores SET tipo_carga='10A80BC', setor='Caldeira' WHERE regiao='Ilhéus' AND numero_int=66;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área vermelha' WHERE regiao='Ilhéus' AND numero_int=67;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Área vermelha' WHERE regiao='Ilhéus' AND numero_int=68;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área vermelha' WHERE regiao='Ilhéus' AND numero_int=69;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Área vermelha' WHERE regiao='Ilhéus' AND numero_int=70;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Caldeira' WHERE regiao='Ilhéus' AND numero_int=71;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área vermelha' WHERE regiao='Ilhéus' AND numero_int=72;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Área vermelha' WHERE regiao='Ilhéus' AND numero_int=73;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área vermelha' WHERE regiao='Ilhéus' AND numero_int=74;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Intermediário' WHERE regiao='Ilhéus' AND numero_int=75;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Intermediário' WHERE regiao='Ilhéus' AND numero_int=76;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Intermediário' WHERE regiao='Ilhéus' AND numero_int=77;
UPDATE extintores SET tipo_carga='10A80BC', setor='Intermediário' WHERE regiao='Ilhéus' AND numero_int=78;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Intermediário' WHERE regiao='Ilhéus' AND numero_int=79;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Intermediário' WHERE regiao='Ilhéus' AND numero_int=80;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Intermediário' WHERE regiao='Ilhéus' AND numero_int=81;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Intermediário' WHERE regiao='Ilhéus' AND numero_int=82;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Robozinho' WHERE regiao='Ilhéus' AND numero_int=83;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Robozinho' WHERE regiao='Ilhéus' AND numero_int=84;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Robozinho' WHERE regiao='Ilhéus' AND numero_int=85;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Robozinho' WHERE regiao='Ilhéus' AND numero_int=86;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Intermediário' WHERE regiao='Ilhéus' AND numero_int=87;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Intermediário' WHERE regiao='Ilhéus' AND numero_int=88;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Embalagem Room' WHERE regiao='Ilhéus' AND numero_int=89;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Intermediário' WHERE regiao='Ilhéus' AND numero_int=90;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Intermediário' WHERE regiao='Ilhéus' AND numero_int=91;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área de refinos' WHERE regiao='Ilhéus' AND numero_int=92;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Área de refinos' WHERE regiao='Ilhéus' AND numero_int=93;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área branca' WHERE regiao='Ilhéus' AND numero_int=94;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Área branca' WHERE regiao='Ilhéus' AND numero_int=95;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área branca' WHERE regiao='Ilhéus' AND numero_int=96;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Área branca' WHERE regiao='Ilhéus' AND numero_int=97;
UPDATE extintores SET tipo_carga='BC 50kg', setor='Área branca' WHERE regiao='Ilhéus' AND numero_int=98;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Área branca' WHERE regiao='Ilhéus' AND numero_int=99;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Caldeira' WHERE regiao='Ilhéus' AND numero_int=100;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Caldeira' WHERE regiao='Ilhéus' AND numero_int=101;
UPDATE extintores SET tipo_carga='10A80BC', setor='Caldeira' WHERE regiao='Ilhéus' AND numero_int=102;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Caldeira' WHERE regiao='Ilhéus' AND numero_int=103;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Caldeira' WHERE regiao='Ilhéus' AND numero_int=104;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Caldeira' WHERE regiao='Ilhéus' AND numero_int=105;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Caldeira' WHERE regiao='Ilhéus' AND numero_int=106;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Compressores' WHERE regiao='Ilhéus' AND numero_int=107;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Área branca' WHERE regiao='Ilhéus' AND numero_int=108;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área branca' WHERE regiao='Ilhéus' AND numero_int=109;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área branca' WHERE regiao='Ilhéus' AND numero_int=110;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Área branca' WHERE regiao='Ilhéus' AND numero_int=111;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Sala de compressores' WHERE regiao='Ilhéus' AND numero_int=112;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Caldeira' WHERE regiao='Ilhéus' AND numero_int=113;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Caldeira' WHERE regiao='Ilhéus' AND numero_int=114;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Caldeira' WHERE regiao='Ilhéus' AND numero_int=115;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área branca' WHERE regiao='Ilhéus' AND numero_int=116;
UPDATE extintores SET tipo_carga='CO2 4kg', setor='Área branca' WHERE regiao='Ilhéus' AND numero_int=117;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Área branca' WHERE regiao='Ilhéus' AND numero_int=118;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área branca' WHERE regiao='Ilhéus' AND numero_int=119;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área de pó' WHERE regiao='Ilhéus' AND numero_int=120;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Área de pó' WHERE regiao='Ilhéus' AND numero_int=121;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Área de pó' WHERE regiao='Ilhéus' AND numero_int=122;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área de pó' WHERE regiao='Ilhéus' AND numero_int=123;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área de pó' WHERE regiao='Ilhéus' AND numero_int=124;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Área de pó' WHERE regiao='Ilhéus' AND numero_int=125;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Próx. Casa de bombas' WHERE regiao='Ilhéus' AND numero_int=126;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Splitao' WHERE regiao='Ilhéus' AND numero_int=127;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Próx. Casa de bombas' WHERE regiao='Ilhéus' AND numero_int=128;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Sanitização - interno' WHERE regiao='Ilhéus' AND numero_int=129;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Próx. Casa de bombas' WHERE regiao='Ilhéus' AND numero_int=130;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Substação - próx. Torre refr' WHERE regiao='Ilhéus' AND numero_int=131;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Substação próx. Torre refr' WHERE regiao='Ilhéus' AND numero_int=132;
UPDATE extintores SET tipo_carga='4A80BC', setor='Substação próx. Torre refr' WHERE regiao='Ilhéus' AND numero_int=133;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Fundo Substação' WHERE regiao='Ilhéus' AND numero_int=134;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Tanque área tratada - fundos' WHERE regiao='Ilhéus' AND numero_int=135;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Tanque área tratada - fundos' WHERE regiao='Ilhéus' AND numero_int=136;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Casa de bombas' WHERE regiao='Ilhéus' AND numero_int=137;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Casa de bombas' WHERE regiao='Ilhéus' AND numero_int=138;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Lado sala terceiros' WHERE regiao='Ilhéus' AND numero_int=139;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Brigada' WHERE regiao='Ilhéus' AND numero_int=140;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Próx. Ponto enc. Brigada' WHERE regiao='Ilhéus' AND numero_int=141;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Armazém prod. Químico' WHERE regiao='Ilhéus' AND numero_int=142;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Armazém prod. Químico' WHERE regiao='Ilhéus' AND numero_int=143;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Próx. Armazém prod. Químico' WHERE regiao='Ilhéus' AND numero_int=144;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Almoxarifado' WHERE regiao='Ilhéus' AND numero_int=145;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Almoxarifado' WHERE regiao='Ilhéus' AND numero_int=146;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Próx. Oficina - Área ext' WHERE regiao='Ilhéus' AND numero_int=147;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Oficina' WHERE regiao='Ilhéus' AND numero_int=148;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Oficina de manut' WHERE regiao='Ilhéus' AND numero_int=149;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Fundo Almoxarifado' WHERE regiao='Ilhéus' AND numero_int=150;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Próx. Oficina - Área ext' WHERE regiao='Ilhéus' AND numero_int=151;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Entrada auditório' WHERE regiao='Ilhéus' AND numero_int=152;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Entrada auditório' WHERE regiao='Ilhéus' AND numero_int=153;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Fundo Almoxarifado' WHERE regiao='Ilhéus' AND numero_int=154;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Caldeiraria' WHERE regiao='Ilhéus' AND numero_int=155;
UPDATE extintores SET tipo_carga='BC 6kg', setor='Caldeiraria' WHERE regiao='Ilhéus' AND numero_int=156;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Caldeiraria' WHERE regiao='Ilhéus' AND numero_int=157;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Caldeiraria' WHERE regiao='Ilhéus' AND numero_int=158;
UPDATE extintores SET tipo_carga='BC 6kg', setor='Caldeiraria' WHERE regiao='Ilhéus' AND numero_int=159;
UPDATE extintores SET tipo_carga='BC 6kg', setor='Caldeiraria' WHERE regiao='Ilhéus' AND numero_int=160;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Próx. Oficina - Terceiros' WHERE regiao='Ilhéus' AND numero_int=161;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Conteinner ATMA' WHERE regiao='Ilhéus' AND numero_int=162;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Conteinner ATMA' WHERE regiao='Ilhéus' AND numero_int=163;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='EDP' WHERE regiao='Ilhéus' AND numero_int=164;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Conteinner 2S' WHERE regiao='Ilhéus' AND numero_int=165;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Conteinner GR' WHERE regiao='Ilhéus' AND numero_int=166;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Óleo lubrificante' WHERE regiao='Ilhéus' AND numero_int=167;
UPDATE extintores SET tipo_carga='ABC 30kg', setor='Óleo lubrificante' WHERE regiao='Ilhéus' AND numero_int=168;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Óleo lubrificante' WHERE regiao='Ilhéus' AND numero_int=169;
UPDATE extintores SET tipo_carga='EM 10L', setor='Óleo lubrificante' WHERE regiao='Ilhéus' AND numero_int=170;
UPDATE extintores SET tipo_carga='EM 10L', setor='Óleo lubrificante' WHERE regiao='Ilhéus' AND numero_int=171;
UPDATE extintores SET tipo_carga='EM 10L', setor='Óleo lubrificante' WHERE regiao='Ilhéus' AND numero_int=172;
UPDATE extintores SET tipo_carga='EM 10L', setor='Óleo lubrificante' WHERE regiao='Ilhéus' AND numero_int=173;
UPDATE extintores SET tipo_carga='BC 6kg', setor='Próx. Resíduos lâmpadas' WHERE regiao='Ilhéus' AND numero_int=174;
UPDATE extintores SET tipo_carga='BC 6kg', setor='Próx. Resíduos lâmpadas' WHERE regiao='Ilhéus' AND numero_int=175;
UPDATE extintores SET tipo_carga='BC 6kg', setor='GLP' WHERE regiao='Ilhéus' AND numero_int=176;
UPDATE extintores SET tipo_carga='BC 6kg', setor='GLP' WHERE regiao='Ilhéus' AND numero_int=177;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Reciclagem' WHERE regiao='Ilhéus' AND numero_int=178;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Reciclagem' WHERE regiao='Ilhéus' AND numero_int=179;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Estoque material' WHERE regiao='Ilhéus' AND numero_int=180;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Estoque material' WHERE regiao='Ilhéus' AND numero_int=181;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Varredura resíduos cacau' WHERE regiao='Ilhéus' AND numero_int=182;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Varredura resíduos cacau' WHERE regiao='Ilhéus' AND numero_int=183;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Resíduos cacau - interno' WHERE regiao='Ilhéus' AND numero_int=184;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Frente Conteinner Luc' WHERE regiao='Ilhéus' AND numero_int=185;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Frente Conteinner Luc' WHERE regiao='Ilhéus' AND numero_int=186;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Garagem Barry - área ext' WHERE regiao='Ilhéus' AND numero_int=187;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Garagem Barry - área ext' WHERE regiao='Ilhéus' AND numero_int=188;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Desmet Pav. 1' WHERE regiao='Ilhéus' AND numero_int=189;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Desmet Pav. 1' WHERE regiao='Ilhéus' AND numero_int=190;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Desmet Pav. 2' WHERE regiao='Ilhéus' AND numero_int=191;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Desmet Pav. 2' WHERE regiao='Ilhéus' AND numero_int=192;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Desmet Pav. 3' WHERE regiao='Ilhéus' AND numero_int=193;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Desmet Pav. 3' WHERE regiao='Ilhéus' AND numero_int=194;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Desmet Pav. 4' WHERE regiao='Ilhéus' AND numero_int=195;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Desmet Pav. 4' WHERE regiao='Ilhéus' AND numero_int=196;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Grantz 1 Pav' WHERE regiao='Ilhéus' AND numero_int=197;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Grantz 1 Pav' WHERE regiao='Ilhéus' AND numero_int=198;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Grantz 2 Pav' WHERE regiao='Ilhéus' AND numero_int=199;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Grantz 2 Pav' WHERE regiao='Ilhéus' AND numero_int=200;
