-- =============================================================================
-- MIGRATION 0020: Ilhéus data part 2 (extintores 201-300) — completes Ilhéus.
-- Idempotent. #208 had an empty "setor:" placeholder → stored as blank setor.
-- =============================================================================
-- 100 extintores Ilhéus (201-300)
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Conimix 2 Pav' WHERE regiao='Ilhéus' AND numero_int=201;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Conimix 2 Pav' WHERE regiao='Ilhéus' AND numero_int=202;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Entrada laje área verm' WHERE regiao='Ilhéus' AND numero_int=203;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Laje área vermelha' WHERE regiao='Ilhéus' AND numero_int=204;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Laje área vermelha' WHERE regiao='Ilhéus' AND numero_int=205;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Manteiga 1° Pav' WHERE regiao='Ilhéus' AND numero_int=206;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Caldeira 1° Pav' WHERE regiao='Ilhéus' AND numero_int=207;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='' WHERE regiao='Ilhéus' AND numero_int=208;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Laboratório sensorial' WHERE regiao='Ilhéus' AND numero_int=209;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Frente lab. Sensorial área ext' WHERE regiao='Ilhéus' AND numero_int=210;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Sala Maq. Compressor amônia' WHERE regiao='Ilhéus' AND numero_int=211;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Sala Maq. Compressor amônia' WHERE regiao='Ilhéus' AND numero_int=212;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Sala Maq. Compressor amônia' WHERE regiao='Ilhéus' AND numero_int=213;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Sala Maq. Compressor amônia' WHERE regiao='Ilhéus' AND numero_int=214;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Sala compressores 1° Pav' WHERE regiao='Ilhéus' AND numero_int=215;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='MRS 123 1° Pav' WHERE regiao='Ilhéus' AND numero_int=216;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área de Pó' WHERE regiao='Ilhéus' AND numero_int=217;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Armazém intermed. 1° Pav' WHERE regiao='Ilhéus' AND numero_int=218;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Armazém intermed. 1° Pav' WHERE regiao='Ilhéus' AND numero_int=219;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área líquida' WHERE regiao='Ilhéus' AND numero_int=220;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Área líquida' WHERE regiao='Ilhéus' AND numero_int=221;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Prensas área branca' WHERE regiao='Ilhéus' AND numero_int=222;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Prensas área líquida' WHERE regiao='Ilhéus' AND numero_int=223;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Prensas área líquida' WHERE regiao='Ilhéus' AND numero_int=224;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Área sólida' WHERE regiao='Ilhéus' AND numero_int=225;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Secador área vermelha' WHERE regiao='Ilhéus' AND numero_int=226;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Caldeira' WHERE regiao='Ilhéus' AND numero_int=227;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Abaixo Plataf. Desmet' WHERE regiao='Ilhéus' AND numero_int=228;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Área branca' WHERE regiao='Ilhéus' AND numero_int=229;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Área de Pó' WHERE regiao='Ilhéus' AND numero_int=230;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Reymond' WHERE regiao='Ilhéus' AND numero_int=231;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Moinho Reymond' WHERE regiao='Ilhéus' AND numero_int=232;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Moinho Reymond' WHERE regiao='Ilhéus' AND numero_int=233;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Reymond' WHERE regiao='Ilhéus' AND numero_int=234;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Produto acabado' WHERE regiao='Ilhéus' AND numero_int=235;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Embalagens' WHERE regiao='Ilhéus' AND numero_int=236;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Oficina' WHERE regiao='Ilhéus' AND numero_int=237;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Manutenção' WHERE regiao='Ilhéus' AND numero_int=238;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Sala compressores amônia 1° Pav' WHERE regiao='Ilhéus' AND numero_int=239;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Acima manutenção' WHERE regiao='Ilhéus' AND numero_int=240;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Rampa ETA' WHERE regiao='Ilhéus' AND numero_int=241;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Rampa ETA' WHERE regiao='Ilhéus' AND numero_int=242;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Conimix 1° Pav' WHERE regiao='Ilhéus' AND numero_int=243;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Conimix 3° Pav. Telhado' WHERE regiao='Ilhéus' AND numero_int=244;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='CCM' WHERE regiao='Ilhéus' AND numero_int=245;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='CCM' WHERE regiao='Ilhéus' AND numero_int=246;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Área branca' WHERE regiao='Ilhéus' AND numero_int=247;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Armazém intermediário' WHERE regiao='Ilhéus' AND numero_int=248;
UPDATE extintores SET tipo_carga='BC 6kg', setor='Área ext. Lado GLP' WHERE regiao='Ilhéus' AND numero_int=249;
UPDATE extintores SET tipo_carga='AP 10L', setor='Upstream' WHERE regiao='Ilhéus' AND numero_int=250;
UPDATE extintores SET tipo_carga='AP 10L', setor='Upstream' WHERE regiao='Ilhéus' AND numero_int=251;
UPDATE extintores SET tipo_carga='AP 10L', setor='Upstream' WHERE regiao='Ilhéus' AND numero_int=252;
UPDATE extintores SET tipo_carga='AP 10L', setor='Upstream' WHERE regiao='Ilhéus' AND numero_int=253;
UPDATE extintores SET tipo_carga='AP 10L', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=254;
UPDATE extintores SET tipo_carga='AP 10L', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=255;
UPDATE extintores SET tipo_carga='AP 10L', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=256;
UPDATE extintores SET tipo_carga='AP 10L', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=257;
UPDATE extintores SET tipo_carga='AP 10L', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=258;
UPDATE extintores SET tipo_carga='AP 10L', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=259;
UPDATE extintores SET tipo_carga='AP 10L', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=260;
UPDATE extintores SET tipo_carga='AP 10L', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=261;
UPDATE extintores SET tipo_carga='AP 10L', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=262;
UPDATE extintores SET tipo_carga='AP 10L', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=263;
UPDATE extintores SET tipo_carga='AP 10L', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=264;
UPDATE extintores SET tipo_carga='AP 10L', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=265;
UPDATE extintores SET tipo_carga='AP 10L', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=266;
UPDATE extintores SET tipo_carga='AP 10L', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=267;
UPDATE extintores SET tipo_carga='AP 10L', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=268;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=269;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=270;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=271;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=272;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=273;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=274;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=275;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=276;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=277;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=278;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=279;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=280;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=281;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=282;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=283;
UPDATE extintores SET tipo_carga='ABC 20kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=284;
UPDATE extintores SET tipo_carga='ABC 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=285;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=286;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=287;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=288;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=289;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=290;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=291;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=292;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=293;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=294;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=295;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=296;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=297;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=298;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=299;
UPDATE extintores SET tipo_carga='CO2 6kg', setor='Reserva' WHERE regiao='Ilhéus' AND numero_int=300;
