-- =============================================================================
-- MIGRATION 0034: seed Phase-2 alarm devices (Fábrica de Itabuna inventory)
--
-- 397 devices from the client's spreadsheet (docs/dispositivos-alarme.csv),
-- across the 4 centrais. Type text normalised to the system's fixed codes:
--   "Detector de Fumaça Pontual"            -> detector_fumaca   (223)
--   "Acionador"/"Acioandor"(typo)           -> acionador         (62)
--   "Sirene"/"Sirenes"                      -> sirene            (48)
--   "Módulo de Acionamento/Falha Detector Linear" -> modulo_supervisao (64)
-- The ORIGINAL type wording is preserved in `descricao` so the Acionamento/Falha
-- distinction isn't lost. central matched by number; laço/endereço as given.
--
-- Adds data_prevista_instalacao (target install date) for the future execution
-- schedule ("cronograma"); left NULL now (the sheet's column was empty).
--
-- Idempotent + non-destructive: upsert by seed_key ('csv|<central>|<laço>|<end>')
-- so re-running never duplicates and never touches manually-edited devices
-- (those have seed_key NULL). Photos/status/observações of already-seeded rows
-- are left intact.
-- =============================================================================

ALTER TABLE dispositivos_alarme
  ADD COLUMN IF NOT EXISTS data_prevista_instalacao DATE;

INSERT INTO dispositivos_alarme
  (central_id, laco, endereco, tipo_dispositivo, setor, descricao, seed_key,
   status_instalacao, cadastro_pendente)
SELECT c.id, v.laco, v.endereco, v.tipo, v.setor, v.descricao, v.seed_key,
       'pendente', false          -- laço+endereço known -> cadastro complete
FROM (VALUES
  (1, 1, '1', 'acionador', 'Portaria', 'Acionador', 'csv|1|1|1'),
  (1, 1, '2', 'acionador', 'Corredor ADM', 'Acionador', 'csv|1|1|2'),
  (1, 1, '3', 'acionador', 'Lavanderia', 'Acionador', 'csv|1|1|3'),
  (1, 1, '4', 'acionador', 'Sala de Treinamentos', 'Acionador', 'csv|1|1|4'),
  (1, 1, '5', 'acionador', 'Gerência/Chefes', 'Acionador', 'csv|1|1|5'),
  (1, 1, '6', 'acionador', 'Recepção Gerência/Chefe', 'Acionador', 'csv|1|1|6'),
  (1, 1, '7', 'acionador', 'Portaria Logística', 'Acionador', 'csv|1|1|7'),
  (1, 1, '93', 'sirene', 'Portaria', 'Sirene', 'csv|1|1|93'),
  (1, 1, '94', 'sirene', 'Corredor ADM', 'Sirene', 'csv|1|1|94'),
  (1, 1, '95', 'sirene', 'Lavanderia', 'Sirene', 'csv|1|1|95'),
  (1, 1, '96', 'sirene', 'Sala de Treinamentos', 'Sirene', 'csv|1|1|96'),
  (1, 1, '97', 'sirene', 'Gerência/Chefes', 'Sirene', 'csv|1|1|97'),
  (1, 1, '98', 'sirene', 'Recepção Gerência/Chefe', 'Sirene', 'csv|1|1|98'),
  (1, 1, '99', 'sirene', 'Portaria Logística', 'Sirene', 'csv|1|1|99'),
  (2, 1, '1', 'acionador', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Acionador', 'csv|2|1|1'),
  (2, 1, '2', 'acionador', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Acionador', 'csv|2|1|2'),
  (2, 1, '3', 'acionador', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Acionador', 'csv|2|1|3'),
  (2, 1, '4', 'acionador', 'Galpão Logística (Lateral a Paletização)', 'Acionador', 'csv|2|1|4'),
  (2, 1, '5', 'acionador', 'Galpão Logística (Lateral a Área Externa)', 'Acionador', 'csv|2|1|5'),
  (2, 1, '6', 'acionador', 'Próximo a Sala de Baterias', 'Acionador', 'csv|2|1|6'),
  (2, 1, '7', 'acionador', 'Galpão Logística - Ampliação Fase 2 (Lateral Sala de Baterias)', 'Acionador', 'csv|2|1|7'),
  (2, 1, '8', 'acionador', 'Armazém de Paletização Logística', 'Acionador', 'csv|2|1|8'),
  (2, 1, '9', 'acionador', 'Corredor Logística', 'Acionador', 'csv|2|1|9'),
  (2, 1, '10', 'acionador', 'Corredor Logística', 'Acionador', 'csv|2|1|10'),
  (2, 1, '11', 'acionador', 'Oficina Mecânica', 'Acionador', 'csv|2|1|11'),
  (2, 1, '12', 'acionador', 'Sala de Ar Comprimido e Gás Inerte', 'Acionador', 'csv|2|1|12'),
  (2, 1, '13', 'acionador', 'Depósito UHT', 'Acionador', 'csv|2|1|13'),
  (2, 1, '14', 'acionador', 'Produto Químico', 'Acionador', 'csv|2|1|14'),
  (2, 1, '15', 'acionador', 'Galpão Pista', 'Acionador', 'csv|2|1|15'),
  (2, 1, '16', 'modulo_supervisao', 'Galpão Logística (Lateral a Paletização)', 'Módulo de Acionamento Detector Linear', 'csv|2|1|16'),
  (2, 1, '17', 'modulo_supervisao', 'Galpão Logística (Lateral a Paletização)', 'Módulo de Falha Detector Linear', 'csv|2|1|17'),
  (2, 1, '18', 'modulo_supervisao', 'Galpão Logística (Lateral a Paletização)', 'Módulo de Acionamento Detector Linear', 'csv|2|1|18'),
  (2, 1, '19', 'modulo_supervisao', 'Galpão Logística (Lateral a Paletização)', 'Módulo de Falha Detector Linear', 'csv|2|1|19'),
  (2, 1, '20', 'modulo_supervisao', 'Galpão Logística (Lateral a Paletização)', 'Módulo de Acionamento Detector Linear', 'csv|2|1|20'),
  (2, 1, '21', 'modulo_supervisao', 'Galpão Logística (Lateral a Paletização)', 'Módulo de Falha Detector Linear', 'csv|2|1|21'),
  (2, 1, '22', 'modulo_supervisao', 'Galpão Logística (Lateral a Paletização)', 'Módulo de Acionamento Detector Linear', 'csv|2|1|22'),
  (2, 1, '23', 'modulo_supervisao', 'Galpão Logística (Lateral a Paletização)', 'Módulo de Falha Detector Linear', 'csv|2|1|23'),
  (2, 1, '24', 'modulo_supervisao', 'Galpão Logística (Lateral a Paletização)', 'Módulo de Acionamento Detector Linear', 'csv|2|1|24'),
  (2, 1, '25', 'modulo_supervisao', 'Galpão Logística (Lateral a Paletização)', 'Módulo de Falha Detector Linear', 'csv|2|1|25'),
  (2, 1, '26', 'modulo_supervisao', 'Galpão Logística (Lateral a Paletização)', 'Módulo de Acionamento Detector Linear', 'csv|2|1|26'),
  (2, 1, '27', 'modulo_supervisao', 'Galpão Logística (Lateral a Paletização)', 'Módulo de Falha Detector Linear', 'csv|2|1|27'),
  (2, 1, '28', 'modulo_supervisao', 'Galpão Logística (Lateral a Área Externa)', 'Módulo de Acionamento Detector Linear', 'csv|2|1|28'),
  (2, 1, '29', 'modulo_supervisao', 'Galpão Logística (Lateral a Área Externa)', 'Módulo de Falha Detector Linear', 'csv|2|1|29'),
  (2, 1, '30', 'modulo_supervisao', 'Galpão Logística (Lateral a Área Externa)', 'Módulo de Acionamento Detector Linear', 'csv|2|1|30'),
  (2, 1, '31', 'modulo_supervisao', 'Galpão Logística (Lateral a Área Externa)', 'Módulo de Falha Detector Linear', 'csv|2|1|31'),
  (2, 1, '32', 'modulo_supervisao', 'Galpão Logística (Lateral a Área Externa)', 'Módulo de Acionamento Detector Linear', 'csv|2|1|32'),
  (2, 1, '33', 'modulo_supervisao', 'Galpão Logística (Lateral a Área Externa)', 'Módulo de Falha Detector Linear', 'csv|2|1|33'),
  (2, 1, '34', 'modulo_supervisao', 'Galpão Logística (Lateral a Área Externa)', 'Módulo de Acionamento Detector Linear', 'csv|2|1|34'),
  (2, 1, '35', 'modulo_supervisao', 'Galpão Logística (Lateral a Área Externa)', 'Módulo de Falha Detector Linear', 'csv|2|1|35'),
  (2, 1, '36', 'modulo_supervisao', 'Galpão Logística (Lateral a Área Externa)', 'Módulo de Acionamento Detector Linear', 'csv|2|1|36'),
  (2, 1, '37', 'modulo_supervisao', 'Galpão Logística (Lateral a Área Externa)', 'Módulo de Falha Detector Linear', 'csv|2|1|37'),
  (2, 1, '38', 'modulo_supervisao', 'Galpão Logística (Lateral a Área Externa)', 'Módulo de Acionamento Detector Linear', 'csv|2|1|38'),
  (2, 1, '39', 'modulo_supervisao', 'Galpão Logística (Lateral a Área Externa)', 'Módulo de Falha Detector Linear', 'csv|2|1|39'),
  (2, 1, '40', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Detector de Fumaça Pontual', 'csv|2|1|40'),
  (2, 1, '41', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Detector de Fumaça Pontual', 'csv|2|1|41'),
  (2, 1, '42', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Detector de Fumaça Pontual', 'csv|2|1|42'),
  (2, 1, '43', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Detector de Fumaça Pontual', 'csv|2|1|43'),
  (2, 1, '44', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Detector de Fumaça Pontual', 'csv|2|1|44'),
  (2, 1, '45', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Detector de Fumaça Pontual', 'csv|2|1|45'),
  (2, 1, '46', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Detector de Fumaça Pontual', 'csv|2|1|46'),
  (2, 1, '47', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Detector de Fumaça Pontual', 'csv|2|1|47'),
  (2, 1, '48', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Detector de Fumaça Pontual', 'csv|2|1|48'),
  (2, 1, '49', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Detector de Fumaça Pontual', 'csv|2|1|49'),
  (2, 1, '50', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Detector de Fumaça Pontual', 'csv|2|1|50'),
  (2, 1, '51', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Detector de Fumaça Pontual', 'csv|2|1|51'),
  (2, 1, '52', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Detector de Fumaça Pontual', 'csv|2|1|52'),
  (2, 1, '53', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Detector de Fumaça Pontual', 'csv|2|1|53'),
  (2, 1, '54', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Detector de Fumaça Pontual', 'csv|2|1|54'),
  (2, 1, '55', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Detector de Fumaça Pontual', 'csv|2|1|55'),
  (2, 1, '56', 'detector_fumaca', 'Sala de Baterias', 'Detector de Fumaça Pontual', 'csv|2|1|56'),
  (2, 1, '57', 'detector_fumaca', 'Sala de Baterias', 'Detector de Fumaça Pontual', 'csv|2|1|57'),
  (2, 1, '58', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 2 (Lateral Sala de Baterias)', 'Detector de Fumaça Pontual', 'csv|2|1|58'),
  (2, 1, '59', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 2 (Lateral Sala de Baterias)', 'Detector de Fumaça Pontual', 'csv|2|1|59'),
  (2, 1, '60', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 2 (Lateral Sala de Baterias)', 'Detector de Fumaça Pontual', 'csv|2|1|60'),
  (2, 1, '61', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 2 (Lateral Sala de Baterias)', 'Detector de Fumaça Pontual', 'csv|2|1|61'),
  (2, 1, '62', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 2 (Lateral Sala de Baterias)', 'Detector de Fumaça Pontual', 'csv|2|1|62'),
  (2, 1, '63', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 2 (Lateral Sala de Baterias)', 'Detector de Fumaça Pontual', 'csv|2|1|63'),
  (2, 1, '64', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 2 (Lateral Sala de Baterias)', 'Detector de Fumaça Pontual', 'csv|2|1|64'),
  (2, 1, '65', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 2 (Lateral Sala de Baterias)', 'Detector de Fumaça Pontual', 'csv|2|1|65'),
  (2, 1, '66', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 2 (Lateral Sala de Baterias)', 'Detector de Fumaça Pontual', 'csv|2|1|66'),
  (2, 1, '67', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 2 (Lateral Sala de Baterias)', 'Detector de Fumaça Pontual', 'csv|2|1|67'),
  (2, 1, '68', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 2 (Lateral Sala de Baterias)', 'Detector de Fumaça Pontual', 'csv|2|1|68'),
  (2, 1, '69', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 2 (Lateral Sala de Baterias)', 'Detector de Fumaça Pontual', 'csv|2|1|69'),
  (2, 1, '70', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 2 (Lateral Sala de Baterias)', 'Detector de Fumaça Pontual', 'csv|2|1|70'),
  (2, 1, '71', 'detector_fumaca', 'Galpão Logística - Ampliação Fase 2 (Lateral Sala de Baterias)', 'Detector de Fumaça Pontual', 'csv|2|1|71'),
  (2, 1, '93', 'sirene', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Sirenes', 'csv|2|1|93'),
  (2, 1, '94', 'sirene', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Sirenes', 'csv|2|1|94'),
  (2, 1, '95', 'sirene', 'Galpão Logística - Ampliação Fase 1 (Lateral Docas)', 'Sirenes', 'csv|2|1|95'),
  (2, 1, '96', 'sirene', 'Galpão Logística (Lateral a Paletização)', 'Sirenes', 'csv|2|1|96'),
  (2, 1, '97', 'sirene', 'Galpão Logística (Lateral a Área Externa)', 'Sirenes', 'csv|2|1|97'),
  (2, 1, '98', 'sirene', 'Próximo a Sala de Baterias', 'Sirenes', 'csv|2|1|98'),
  (2, 1, '99', 'sirene', 'Galpão Logística - Ampliação Fase 2 (Lateral Sala de Baterias)', 'Sirenes', 'csv|2|1|99'),
  (2, 1, '100', 'sirene', 'Armazém de Paletização Logística', 'Sirenes', 'csv|2|1|100'),
  (2, 1, '101', 'sirene', 'Corredor Logística', 'Sirenes', 'csv|2|1|101'),
  (2, 1, '102', 'sirene', 'Corredor Logística', 'Sirenes', 'csv|2|1|102'),
  (2, 1, '103', 'sirene', 'Oficina Mecânica', 'Sirenes', 'csv|2|1|103'),
  (2, 1, '104', 'sirene', 'Sala de Ar Comprimido e Gás Inerte', 'Sirenes', 'csv|2|1|104'),
  (2, 1, '105', 'sirene', 'Depósito UHT', 'Sirenes', 'csv|2|1|105'),
  (2, 1, '106', 'sirene', 'Produto Químico', 'Sirenes', 'csv|2|1|106'),
  (2, 1, '107', 'sirene', 'Galpão Pista', 'Sirenes', 'csv|2|1|107'),
  (3, 1, '1', 'acionador', 'Próximo a Central da Fábrica', 'Acioandor', 'csv|3|1|1'),
  (3, 1, '2', 'acionador', 'Próximo a Sala de Painéis/Trafos da Fábrica', 'Acionador', 'csv|3|1|2'),
  (3, 1, '3', 'acionador', 'Armazém de Favas 1', 'Acionador', 'csv|3|1|3'),
  (3, 1, '4', 'acionador', 'Armazém de Favas 1', 'Acionador', 'csv|3|1|4'),
  (3, 1, '5', 'acionador', 'Armazém de Favas 2', 'Acionador', 'csv|3|1|5'),
  (3, 1, '6', 'acionador', 'Armazém de Favas 2', 'Acionador', 'csv|3|1|6'),
  (3, 1, '7', 'acionador', 'Externo Armazém de Favas 2', 'Acionador', 'csv|3|1|7'),
  (3, 1, '8', 'acionador', 'Externo Armazém de Favas 2', 'Acionador', 'csv|3|1|8'),
  (3, 1, '9', 'acionador', 'Separação Cascas Cacau', 'Acionador', 'csv|3|1|9'),
  (3, 1, '10', 'acionador', 'Separação Cascas Cacau', 'Acionador', 'csv|3|1|10'),
  (3, 1, '11', 'acionador', 'Separação Linha 2', 'Acionador', 'csv|3|1|11'),
  (3, 1, '12', 'acionador', 'Torrefação 2', 'Acionador', 'csv|3|1|12'),
  (3, 1, '13', 'acionador', 'Torrefação 2', 'Acionador', 'csv|3|1|13'),
  (3, 1, '14', 'acionador', 'Torrefação', 'Acionador', 'csv|3|1|14'),
  (3, 1, '15', 'acionador', 'Área Branca', 'Acionador', 'csv|3|1|15'),
  (3, 1, '16', 'acionador', 'Área Branca', 'Acionador', 'csv|3|1|16'),
  (3, 1, '17', 'acionador', 'Moagem 2', 'Acionador', 'csv|3|1|17'),
  (3, 1, '18', 'acionador', 'Moagem 2', 'Acionador', 'csv|3|1|18'),
  (3, 1, '19', 'acionador', 'Moagem 2', 'Acionador', 'csv|3|1|19'),
  (3, 1, '20', 'acionador', 'Laboratório', 'Acionador', 'csv|3|1|20'),
  (3, 1, '21', 'acionador', 'Escritório Favas', 'Acionador', 'csv|3|1|21'),
  (3, 1, '22', 'modulo_supervisao', 'Armazém de Favas 1', 'Módulo de Acionamento Detector Linear', 'csv|3|1|22'),
  (3, 1, '23', 'modulo_supervisao', 'Armazém de Favas 1', 'Módulo de Falha Detector Linear', 'csv|3|1|23'),
  (3, 1, '24', 'modulo_supervisao', 'Armazém de Favas 1', 'Módulo de Acionamento Detector Linear', 'csv|3|1|24'),
  (3, 1, '25', 'modulo_supervisao', 'Armazém de Favas 1', 'Módulo de Falha Detector Linear', 'csv|3|1|25'),
  (3, 1, '26', 'modulo_supervisao', 'Armazém de Favas 1', 'Módulo de Acionamento Detector Linear', 'csv|3|1|26'),
  (3, 1, '27', 'modulo_supervisao', 'Armazém de Favas 1', 'Módulo de Falha Detector Linear', 'csv|3|1|27'),
  (3, 1, '28', 'modulo_supervisao', 'Armazém de Favas 1', 'Módulo de Acionamento Detector Linear', 'csv|3|1|28'),
  (3, 1, '29', 'modulo_supervisao', 'Armazém de Favas 1', 'Módulo de Falha Detector Linear', 'csv|3|1|29'),
  (3, 1, '30', 'modulo_supervisao', 'Armazém de Favas 2', 'Módulo de Acionamento Detector Linear', 'csv|3|1|30'),
  (3, 1, '31', 'modulo_supervisao', 'Armazém de Favas 2', 'Módulo de Falha Detector Linear', 'csv|3|1|31'),
  (3, 1, '32', 'modulo_supervisao', 'Armazém de Favas 2', 'Módulo de Acionamento Detector Linear', 'csv|3|1|32'),
  (3, 1, '33', 'modulo_supervisao', 'Armazém de Favas 2', 'Módulo de Falha Detector Linear', 'csv|3|1|33'),
  (3, 1, '34', 'modulo_supervisao', 'Armazém de Favas 2', 'Módulo de Acionamento Detector Linear', 'csv|3|1|34'),
  (3, 1, '35', 'modulo_supervisao', 'Armazém de Favas 2', 'Módulo de Falha Detector Linear', 'csv|3|1|35'),
  (3, 1, '36', 'modulo_supervisao', 'Armazém de Favas 2', 'Módulo de Acionamento Detector Linear', 'csv|3|1|36'),
  (3, 1, '37', 'modulo_supervisao', 'Armazém de Favas 2', 'Módulo de Falha Detector Linear', 'csv|3|1|37'),
  (3, 1, '38', 'detector_fumaca', 'Sala Externa Favas', 'Detector de Fumaça Pontual', 'csv|3|1|38'),
  (3, 1, '39', 'detector_fumaca', 'Sala Externa Favas', 'Detector de Fumaça Pontual', 'csv|3|1|39'),
  (3, 1, '40', 'detector_fumaca', 'Sala Favas', 'Detector de Fumaça Pontual', 'csv|3|1|40'),
  (3, 1, '41', 'detector_fumaca', 'Separação Linha 2', 'Detector de Fumaça Pontual', 'csv|3|1|41'),
  (3, 1, '42', 'detector_fumaca', 'Separação Linha 2', 'Detector de Fumaça Pontual', 'csv|3|1|42'),
  (3, 1, '43', 'detector_fumaca', 'Separação Linha 2', 'Detector de Fumaça Pontual', 'csv|3|1|43'),
  (3, 1, '44', 'detector_fumaca', 'Separação Linha 2', 'Detector de Fumaça Pontual', 'csv|3|1|44'),
  (3, 1, '45', 'detector_fumaca', 'Separação Linha 2', 'Detector de Fumaça Pontual', 'csv|3|1|45'),
  (3, 1, '46', 'detector_fumaca', 'Separação Cascas Cacau', 'Detector de Fumaça Pontual', 'csv|3|1|46'),
  (3, 1, '47', 'detector_fumaca', 'Separação Cascas Cacau', 'Detector de Fumaça Pontual', 'csv|3|1|47'),
  (3, 1, '48', 'detector_fumaca', 'Separação Cascas Cacau', 'Detector de Fumaça Pontual', 'csv|3|1|48'),
  (3, 1, '49', 'detector_fumaca', 'Separação Cascas Cacau', 'Detector de Fumaça Pontual', 'csv|3|1|49'),
  (3, 1, '50', 'detector_fumaca', 'Torrefação', 'Detector de Fumaça Pontual', 'csv|3|1|50'),
  (3, 1, '51', 'detector_fumaca', 'Torrefação', 'Detector de Fumaça Pontual', 'csv|3|1|51'),
  (3, 1, '52', 'detector_fumaca', 'Torrefação', 'Detector de Fumaça Pontual', 'csv|3|1|52'),
  (3, 1, '53', 'detector_fumaca', 'Torrefação', 'Detector de Fumaça Pontual', 'csv|3|1|53'),
  (3, 1, '54', 'detector_fumaca', 'Torrefação', 'Detector de Fumaça Pontual', 'csv|3|1|54'),
  (3, 1, '55', 'detector_fumaca', 'Torrefação 2', 'Detector de Fumaça Pontual', 'csv|3|1|55'),
  (3, 1, '56', 'detector_fumaca', 'Torrefação 2', 'Detector de Fumaça Pontual', 'csv|3|1|56'),
  (3, 1, '57', 'detector_fumaca', 'Torrefação 2', 'Detector de Fumaça Pontual', 'csv|3|1|57'),
  (3, 1, '58', 'detector_fumaca', 'Torrefação 2', 'Detector de Fumaça Pontual', 'csv|3|1|58'),
  (3, 1, '59', 'detector_fumaca', 'Torrefação 2', 'Detector de Fumaça Pontual', 'csv|3|1|59'),
  (3, 1, '60', 'detector_fumaca', 'Torrefação 2', 'Detector de Fumaça Pontual', 'csv|3|1|60'),
  (3, 1, '61', 'detector_fumaca', 'Moagem 2', 'Detector de Fumaça Pontual', 'csv|3|1|61'),
  (3, 1, '62', 'detector_fumaca', 'Moagem 2', 'Detector de Fumaça Pontual', 'csv|3|1|62'),
  (3, 1, '63', 'detector_fumaca', 'Moagem 2', 'Detector de Fumaça Pontual', 'csv|3|1|63'),
  (3, 1, '64', 'detector_fumaca', 'Moagem 2', 'Detector de Fumaça Pontual', 'csv|3|1|64'),
  (3, 1, '65', 'detector_fumaca', 'Moagem 2', 'Detector de Fumaça Pontual', 'csv|3|1|65'),
  (3, 1, '66', 'detector_fumaca', 'Moagem 2', 'Detector de Fumaça Pontual', 'csv|3|1|66'),
  (3, 1, '67', 'detector_fumaca', 'Área Branca', 'Detector de Fumaça Pontual', 'csv|3|1|67'),
  (3, 1, '68', 'detector_fumaca', 'Área Branca', 'Detector de Fumaça Pontual', 'csv|3|1|68'),
  (3, 1, '69', 'detector_fumaca', 'Área Branca', 'Detector de Fumaça Pontual', 'csv|3|1|69'),
  (3, 1, '70', 'detector_fumaca', 'Área Branca', 'Detector de Fumaça Pontual', 'csv|3|1|70'),
  (3, 1, '71', 'detector_fumaca', 'Área Branca', 'Detector de Fumaça Pontual', 'csv|3|1|71'),
  (3, 1, '72', 'detector_fumaca', 'Área Branca', 'Detector de Fumaça Pontual', 'csv|3|1|72'),
  (3, 1, '73', 'detector_fumaca', 'Área Branca', 'Detector de Fumaça Pontual', 'csv|3|1|73'),
  (3, 1, '74', 'detector_fumaca', 'Área Branca', 'Detector de Fumaça Pontual', 'csv|3|1|74'),
  (3, 1, '75', 'detector_fumaca', 'Área Branca', 'Detector de Fumaça Pontual', 'csv|3|1|75'),
  (3, 1, '76', 'detector_fumaca', 'Área Branca', 'Detector de Fumaça Pontual', 'csv|3|1|76'),
  (3, 1, '77', 'detector_fumaca', 'Área Branca', 'Detector de Fumaça Pontual', 'csv|3|1|77'),
  (3, 1, '78', 'detector_fumaca', 'Laboratório', 'Detector de Fumaça Pontual', 'csv|3|1|78'),
  (3, 1, '79', 'detector_fumaca', 'Laboratório', 'Detector de Fumaça Pontual', 'csv|3|1|79'),
  (3, 1, '80', 'detector_fumaca', 'Laboratório', 'Detector de Fumaça Pontual', 'csv|3|1|80'),
  (3, 1, '81', 'detector_fumaca', 'Laboratório', 'Detector de Fumaça Pontual', 'csv|3|1|81'),
  (3, 1, '82', 'detector_fumaca', 'Laboratório', 'Detector de Fumaça Pontual', 'csv|3|1|82'),
  (3, 1, '83', 'detector_fumaca', 'Laboratório', 'Detector de Fumaça Pontual', 'csv|3|1|83'),
  (3, 1, '84', 'detector_fumaca', 'Laboratório', 'Detector de Fumaça Pontual', 'csv|3|1|84'),
  (3, 1, '85', 'detector_fumaca', 'Laboratório', 'Detector de Fumaça Pontual', 'csv|3|1|85'),
  (3, 1, '86', 'detector_fumaca', 'Laboratório', 'Detector de Fumaça Pontual', 'csv|3|1|86'),
  (3, 1, '87', 'detector_fumaca', 'Laboratório', 'Detector de Fumaça Pontual', 'csv|3|1|87'),
  (3, 1, '88', 'detector_fumaca', 'Laboratório', 'Detector de Fumaça Pontual', 'csv|3|1|88'),
  (3, 1, '89', 'detector_fumaca', 'Sala de Painéis Fábrica', 'Detector de Fumaça Pontual', 'csv|3|1|89'),
  (3, 1, '90', 'detector_fumaca', '', 'Detector de Fumaça Pontual', 'csv|3|1|90'),
  (3, 1, '91', 'detector_fumaca', 'Trafos Fábrica', 'Detector de Fumaça Pontual', 'csv|3|1|91'),
  (3, 1, '93', 'sirene', 'Próximo a Central 3 da Fábrica', 'Sirene', 'csv|3|1|93'),
  (3, 1, '94', 'sirene', 'Próximo a Sala de Painéis/Trafos da Fábrica', 'Sirene', 'csv|3|1|94'),
  (3, 1, '95', 'sirene', 'Armazém de Favas 1', 'Sirene', 'csv|3|1|95'),
  (3, 1, '96', 'sirene', 'Armazém de Favas 1', 'Sirene', 'csv|3|1|96'),
  (3, 1, '97', 'sirene', 'Armazém de Favas 2', 'Sirene', 'csv|3|1|97'),
  (3, 1, '98', 'sirene', 'Armazém de Favas 2', 'Sirene', 'csv|3|1|98'),
  (3, 1, '99', 'sirene', 'Externo Armazém de Favas 2', 'Sirene', 'csv|3|1|99'),
  (3, 1, '100', 'sirene', 'Externo Armazém de Favas 2', 'Sirene', 'csv|3|1|100'),
  (3, 1, '101', 'sirene', 'Separação Cascas Cacau', 'Sirene', 'csv|3|1|101'),
  (3, 1, '102', 'sirene', 'Separação Cascas Cacau', 'Sirene', 'csv|3|1|102'),
  (3, 1, '103', 'sirene', 'Separação Linha 2', 'Sirene', 'csv|3|1|103'),
  (3, 1, '104', 'sirene', 'Torrefação 2', 'Sirene', 'csv|3|1|104'),
  (3, 1, '105', 'sirene', 'Torrefação 2', 'Sirene', 'csv|3|1|105'),
  (3, 1, '106', 'sirene', 'Torrefação', 'Sirene', 'csv|3|1|106'),
  (3, 1, '107', 'sirene', 'Área Branca', 'Sirene', 'csv|3|1|107'),
  (3, 1, '108', 'sirene', 'Área Branca', 'Sirene', 'csv|3|1|108'),
  (3, 1, '109', 'sirene', 'Moagem 2', 'Sirene', 'csv|3|1|109'),
  (3, 1, '110', 'sirene', 'Moagem 2', 'Sirene', 'csv|3|1|110'),
  (3, 1, '111', 'sirene', 'Moagem 2', 'Sirene', 'csv|3|1|111'),
  (3, 1, '112', 'sirene', 'Laboratório', 'Sirene', 'csv|3|1|112'),
  (3, 1, '113', 'sirene', 'Escritório Favas', 'Sirene', 'csv|3|1|113'),
  (3, 2, '1', 'acionador', 'Embalagem de Manteiga', 'Acionador', 'csv|3|2|1'),
  (3, 2, '2', 'acionador', 'Pulverização Fase II', 'Acionador', 'csv|3|2|2'),
  (3, 2, '3', 'acionador', 'Pulverização', 'Acionador', 'csv|3|2|3'),
  (3, 2, '4', 'acionador', 'Prensa 2', 'Acionador', 'csv|3|2|4'),
  (3, 2, '5', 'acionador', 'Prensa 2', 'Acionador', 'csv|3|2|5'),
  (3, 2, '6', 'acionador', 'Prensa 3-4-5', 'Acionador', 'csv|3|2|6'),
  (3, 2, '7', 'acionador', 'Prensa 3-4-5', 'Acionador', 'csv|3|2|7'),
  (3, 2, '8', 'acionador', 'Sala de Utilidades', 'Acionador', 'csv|3|2|8'),
  (3, 2, '9', 'acionador', 'Pulverização Linha 2', 'Acionador', 'csv|3|2|9'),
  (3, 2, '10', 'acionador', 'Paletização Produto Acabado', 'Acionador', 'csv|3|2|10'),
  (3, 2, '11', 'acionador', 'Paletização Produto Acabado', 'Acionador', 'csv|3|2|11'),
  (3, 2, '12', 'acionador', 'Armazém de Produto acabado', 'Acionador', 'csv|3|2|12'),
  (3, 2, '13', 'acionador', 'Armazém de Produto acabado', 'Acionador', 'csv|3|2|13'),
  (3, 2, '14', 'acionador', 'Armazém de Produto acabado', 'Acionador', 'csv|3|2|14'),
  (3, 2, '15', 'modulo_supervisao', 'Paletização Produto Acabado', 'Módulo de Acionamento Detector Linear', 'csv|3|2|15'),
  (3, 2, '16', 'modulo_supervisao', 'Paletização Produto Acabado', 'Módulo de Falha Detector Linear', 'csv|3|2|16'),
  (3, 2, '17', 'modulo_supervisao', 'Paletização Produto Acabado', 'Módulo de Acionamento Detector Linear', 'csv|3|2|17'),
  (3, 2, '18', 'modulo_supervisao', 'Paletização Produto Acabado', 'Módulo de Falha Detector Linear', 'csv|3|2|18'),
  (3, 2, '19', 'modulo_supervisao', 'Paletização Produto Acabado', 'Módulo de Acionamento Detector Linear', 'csv|3|2|19'),
  (3, 2, '20', 'modulo_supervisao', 'Paletização Produto Acabado', 'Módulo de Falha Detector Linear', 'csv|3|2|20'),
  (3, 2, '21', 'modulo_supervisao', 'Paletização Produto Acabado', 'Módulo de Acionamento Detector Linear', 'csv|3|2|21'),
  (3, 2, '22', 'modulo_supervisao', 'Paletização Produto Acabado', 'Módulo de Falha Detector Linear', 'csv|3|2|22'),
  (3, 2, '23', 'modulo_supervisao', 'Paletização Produto Acabado', 'Módulo de Acionamento Detector Linear', 'csv|3|2|23'),
  (3, 2, '24', 'modulo_supervisao', 'Paletização Produto Acabado', 'Módulo de Falha Detector Linear', 'csv|3|2|24'),
  (3, 2, '25', 'modulo_supervisao', 'Paletização Produto Acabado', 'Módulo de Acionamento Detector Linear', 'csv|3|2|25'),
  (3, 2, '26', 'modulo_supervisao', 'Paletização Produto Acabado', 'Módulo de Falha Detector Linear', 'csv|3|2|26'),
  (3, 2, '27', 'modulo_supervisao', 'Armazém Produto Acabado', 'Módulo de Acionamento Detector Linear', 'csv|3|2|27'),
  (3, 2, '28', 'modulo_supervisao', 'Armazém Produto Acabado', 'Módulo de Falha Detector Linear', 'csv|3|2|28'),
  (3, 2, '29', 'modulo_supervisao', 'Armazém Produto Acabado', 'Módulo de Acionamento Detector Linear', 'csv|3|2|29'),
  (3, 2, '30', 'modulo_supervisao', 'Armazém Produto Acabado', 'Módulo de Falha Detector Linear', 'csv|3|2|30'),
  (3, 2, '31', 'modulo_supervisao', 'Armazém Produto Acabado', 'Módulo de Acionamento Detector Linear', 'csv|3|2|31'),
  (3, 2, '32', 'modulo_supervisao', 'Armazém Produto Acabado', 'Módulo de Falha Detector Linear', 'csv|3|2|32'),
  (3, 2, '33', 'modulo_supervisao', 'Armazém Produto Acabado', 'Módulo de Acionamento Detector Linear', 'csv|3|2|33'),
  (3, 2, '34', 'modulo_supervisao', 'Armazém Produto Acabado', 'Módulo de Falha Detector Linear', 'csv|3|2|34'),
  (3, 2, '35', 'modulo_supervisao', 'Armazém Produto Acabado', 'Módulo de Acionamento Detector Linear', 'csv|3|2|35'),
  (3, 2, '36', 'modulo_supervisao', 'Armazém Produto Acabado', 'Módulo de Falha Detector Linear', 'csv|3|2|36'),
  (3, 2, '37', 'modulo_supervisao', 'Armazém Produto Acabado', 'Módulo de Acionamento Detector Linear', 'csv|3|2|37'),
  (3, 2, '38', 'modulo_supervisao', 'Armazém Produto Acabado', 'Módulo de Falha Detector Linear', 'csv|3|2|38'),
  (3, 2, '39', 'detector_fumaca', 'Embalagem Manteiga', 'Detector de Fumaça Pontual', 'csv|3|2|39'),
  (3, 2, '40', 'detector_fumaca', 'Embalagem Manteiga', 'Detector de Fumaça Pontual', 'csv|3|2|40'),
  (3, 2, '41', 'detector_fumaca', 'Embalagem Manteiga', 'Detector de Fumaça Pontual', 'csv|3|2|41'),
  (3, 2, '42', 'detector_fumaca', 'Pulverização Fase 2', 'Detector de Fumaça Pontual', 'csv|3|2|42'),
  (3, 2, '43', 'detector_fumaca', 'Pulverização Fase 2', 'Detector de Fumaça Pontual', 'csv|3|2|43'),
  (3, 2, '44', 'detector_fumaca', 'Pulverização Fase 2', 'Detector de Fumaça Pontual', 'csv|3|2|44'),
  (3, 2, '45', 'detector_fumaca', 'Pulverização Fase 2', 'Detector de Fumaça Pontual', 'csv|3|2|45'),
  (3, 2, '46', 'detector_fumaca', 'Pulverização Fase 2', 'Detector de Fumaça Pontual', 'csv|3|2|46'),
  (3, 2, '47', 'detector_fumaca', 'Pulverização 1', 'Detector de Fumaça Pontual', 'csv|3|2|47'),
  (3, 2, '48', 'detector_fumaca', 'Pulverização 1', 'Detector de Fumaça Pontual', 'csv|3|2|48'),
  (3, 2, '49', 'detector_fumaca', 'Próximo a Prensa 3', 'Detector de Fumaça Pontual', 'csv|3|2|49'),
  (3, 2, '50', 'detector_fumaca', 'Próximo a Prensa 3', 'Detector de Fumaça Pontual', 'csv|3|2|50'),
  (3, 2, '51', 'detector_fumaca', 'Prensa 3', 'Detector de Fumaça Pontual', 'csv|3|2|51'),
  (3, 2, '52', 'detector_fumaca', 'Prensa 3', 'Detector de Fumaça Pontual', 'csv|3|2|52'),
  (3, 2, '53', 'detector_fumaca', 'Prensa 3', 'Detector de Fumaça Pontual', 'csv|3|2|53'),
  (3, 2, '54', 'detector_fumaca', 'Prensa 3-4-5', 'Detector de Fumaça Pontual', 'csv|3|2|54'),
  (3, 2, '55', 'detector_fumaca', 'Prensa 3-4-5', 'Detector de Fumaça Pontual', 'csv|3|2|55'),
  (3, 2, '56', 'detector_fumaca', 'Prensa 3-4-5', 'Detector de Fumaça Pontual', 'csv|3|2|56'),
  (3, 2, '57', 'detector_fumaca', 'Prensa 3-4-5', 'Detector de Fumaça Pontual', 'csv|3|2|57'),
  (3, 2, '58', 'detector_fumaca', 'Prensa 3-4-5', 'Detector de Fumaça Pontual', 'csv|3|2|58'),
  (3, 2, '59', 'detector_fumaca', 'Prensa 3-4-5', 'Detector de Fumaça Pontual', 'csv|3|2|59'),
  (3, 2, '60', 'detector_fumaca', 'Prensa 3-4-5', 'Detector de Fumaça Pontual', 'csv|3|2|60'),
  (3, 2, '61', 'detector_fumaca', 'Prensa 3-4-5', 'Detector de Fumaça Pontual', 'csv|3|2|61'),
  (3, 2, '62', 'detector_fumaca', 'Prensa 3-4-5', 'Detector de Fumaça Pontual', 'csv|3|2|62'),
  (3, 2, '63', 'detector_fumaca', 'Sala de Utilidades', 'Detector de Fumaça Pontual', 'csv|3|2|63'),
  (3, 2, '64', 'detector_fumaca', 'Sala de Utilidades', 'Detector de Fumaça Pontual', 'csv|3|2|64'),
  (3, 2, '65', 'detector_fumaca', 'Sala de Utilidades', 'Detector de Fumaça Pontual', 'csv|3|2|65'),
  (3, 2, '66', 'detector_fumaca', 'Sala de Utilidades', 'Detector de Fumaça Pontual', 'csv|3|2|66'),
  (3, 2, '67', 'detector_fumaca', 'Pulverização Linha 3', 'Detector de Fumaça Pontual', 'csv|3|2|67'),
  (3, 2, '68', 'detector_fumaca', 'Pulverização Linha 3', 'Detector de Fumaça Pontual', 'csv|3|2|68'),
  (3, 2, '69', 'detector_fumaca', 'Pulverização Linha 3', 'Detector de Fumaça Pontual', 'csv|3|2|69'),
  (3, 2, '70', 'detector_fumaca', 'Pulverização Linha 3', 'Detector de Fumaça Pontual', 'csv|3|2|70'),
  (3, 2, '71', 'detector_fumaca', 'Pulverização Linha 3', 'Detector de Fumaça Pontual', 'csv|3|2|71'),
  (3, 2, '72', 'detector_fumaca', 'Pulverização Linha 3', 'Detector de Fumaça Pontual', 'csv|3|2|72'),
  (3, 2, '73', 'detector_fumaca', 'Pulverização Linha 3', 'Detector de Fumaça Pontual', 'csv|3|2|73'),
  (3, 2, '74', 'detector_fumaca', 'Pulverização Linha 3', 'Detector de Fumaça Pontual', 'csv|3|2|74'),
  (3, 2, '75', 'detector_fumaca', 'Salas Almoxarifado', 'Detector de Fumaça Pontual', 'csv|3|2|75'),
  (3, 2, '76', 'detector_fumaca', 'Salas Almoxarifado', 'Detector de Fumaça Pontual', 'csv|3|2|76'),
  (3, 2, '77', 'detector_fumaca', 'Salas Almoxarifado', 'Detector de Fumaça Pontual', 'csv|3|2|77'),
  (3, 2, '78', 'detector_fumaca', 'Salas Almoxarifado', 'Detector de Fumaça Pontual', 'csv|3|2|78'),
  (3, 2, '79', 'detector_fumaca', 'Salas Almoxarifado', 'Detector de Fumaça Pontual', 'csv|3|2|79'),
  (3, 2, '80', 'detector_fumaca', 'Salas Almoxarifado', 'Detector de Fumaça Pontual', 'csv|3|2|80'),
  (3, 2, '81', 'detector_fumaca', 'Salas Almoxarifado', 'Detector de Fumaça Pontual', 'csv|3|2|81'),
  (3, 2, '82', 'detector_fumaca', 'Salas Almoxarifado', 'Detector de Fumaça Pontual', 'csv|3|2|82'),
  (3, 2, '83', 'detector_fumaca', 'Salas Almoxarifado', 'Detector de Fumaça Pontual', 'csv|3|2|83'),
  (3, 2, '84', 'detector_fumaca', 'Salas Almoxarifado', 'Detector de Fumaça Pontual', 'csv|3|2|84'),
  (3, 2, '85', 'detector_fumaca', 'Salas Almoxarifado', 'Detector de Fumaça Pontual', 'csv|3|2|85'),
  (3, 2, '86', 'detector_fumaca', 'Lubrificantes e Inflamáveis', 'Detector de Fumaça Pontual', 'csv|3|2|86'),
  (3, 2, '87', 'detector_fumaca', 'Depósito Químicos', 'Detector de Fumaça Pontual', 'csv|3|2|87'),
  (3, 3, '1', 'detector_fumaca', 'Mezanino - Armazém de Favas - Linha 2 - Nivel 1', 'Detector de Fumaça Pontual', 'csv|3|3|1'),
  (3, 3, '2', 'detector_fumaca', 'Mezanino - Limpeza de Favas', 'Detector de Fumaça Pontual', 'csv|3|3|2'),
  (3, 3, '3', 'detector_fumaca', 'Mezanino - Tratamento de Cascas - Nivel 2', 'Detector de Fumaça Pontual', 'csv|3|3|3'),
  (3, 3, '4', 'detector_fumaca', 'Mezanino - Separação Cascas de Cacau', 'Detector de Fumaça Pontual', 'csv|3|3|4'),
  (3, 3, '5', 'detector_fumaca', 'Mezanino - Separação Cascas de Cacau', 'Detector de Fumaça Pontual', 'csv|3|3|5'),
  (3, 3, '6', 'detector_fumaca', 'Mezanino - Separação Cascas de Cacau', 'Detector de Fumaça Pontual', 'csv|3|3|6'),
  (3, 3, '7', 'detector_fumaca', 'Mezanino - Separação Linha 2', 'Detector de Fumaça Pontual', 'csv|3|3|7'),
  (3, 3, '8', 'detector_fumaca', 'Mezanino - Separação Linha 3', 'Detector de Fumaça Pontual', 'csv|3|3|8'),
  (3, 3, '9', 'detector_fumaca', 'Mezanino - Separação Linha 4', 'Detector de Fumaça Pontual', 'csv|3|3|9'),
  (3, 3, '10', 'detector_fumaca', 'Mezanino - Separação Cascas de Cacau - Nivel 2', 'Detector de Fumaça Pontual', 'csv|3|3|10'),
  (3, 3, '11', 'detector_fumaca', 'Mezanino - Separação Cascas de Cacau - Nivel 2', 'Detector de Fumaça Pontual', 'csv|3|3|11'),
  (3, 3, '12', 'detector_fumaca', 'Mezanino - Separação Cascas de Cacau - Nivel 3', 'Detector de Fumaça Pontual', 'csv|3|3|12'),
  (3, 3, '13', 'detector_fumaca', 'Mezanino - Separação Cascas de Cacau - Nivel 3', 'Detector de Fumaça Pontual', 'csv|3|3|13'),
  (3, 3, '14', 'detector_fumaca', 'Mezanino - Separação Cascas de Cacau - Nivel 3', 'Detector de Fumaça Pontual', 'csv|3|3|14'),
  (3, 3, '15', 'detector_fumaca', 'Mezanino - Separação Cascas de Cacau - Nivel 4', 'Detector de Fumaça Pontual', 'csv|3|3|15'),
  (3, 3, '16', 'detector_fumaca', 'Mezanino - Torrefação', 'Detector de Fumaça Pontual', 'csv|3|3|16'),
  (3, 3, '17', 'detector_fumaca', 'Mezanino - Torrefação', 'Detector de Fumaça Pontual', 'csv|3|3|17'),
  (3, 3, '18', 'detector_fumaca', 'Mezanino - Torrefação', 'Detector de Fumaça Pontual', 'csv|3|3|18'),
  (3, 3, '19', 'detector_fumaca', 'Mezanino - Torrefação', 'Detector de Fumaça Pontual', 'csv|3|3|19'),
  (3, 3, '20', 'detector_fumaca', 'Mezanino - Torrefação', 'Detector de Fumaça Pontual', 'csv|3|3|20'),
  (3, 3, '21', 'detector_fumaca', 'Mezanino - Torrefação PV 2', 'Detector de Fumaça Pontual', 'csv|3|3|21'),
  (3, 3, '22', 'detector_fumaca', 'Mezanino - Torrefação 2', 'Detector de Fumaça Pontual', 'csv|3|3|22'),
  (3, 3, '23', 'detector_fumaca', 'Mezanino - Torrefação 2', 'Detector de Fumaça Pontual', 'csv|3|3|23'),
  (3, 3, '24', 'detector_fumaca', 'Mezanino - Sala de Painéis Torrefação', 'Detector de Fumaça Pontual', 'csv|3|3|24'),
  (3, 3, '25', 'detector_fumaca', 'Mezanino - Área de Prensa', 'Detector de Fumaça Pontual', 'csv|3|3|25'),
  (3, 3, '26', 'detector_fumaca', 'Mezanino - Área de Prensa', 'Detector de Fumaça Pontual', 'csv|3|3|26'),
  (3, 3, '27', 'detector_fumaca', 'Mezanino - Moagem 2', 'Detector de Fumaça Pontual', 'csv|3|3|27'),
  (3, 3, '28', 'detector_fumaca', 'Mezanino - Moagem 2', 'Detector de Fumaça Pontual', 'csv|3|3|28'),
  (3, 3, '29', 'detector_fumaca', 'Mezanino - Moagem 2', 'Detector de Fumaça Pontual', 'csv|3|3|29'),
  (3, 3, '30', 'detector_fumaca', 'Mezanino - Moagem 2', 'Detector de Fumaça Pontual', 'csv|3|3|30'),
  (3, 3, '31', 'detector_fumaca', 'Mezanino - Sala Administrativa', 'Detector de Fumaça Pontual', 'csv|3|3|31'),
  (3, 3, '32', 'detector_fumaca', 'Mezanino - Sala Administrativa', 'Detector de Fumaça Pontual', 'csv|3|3|32'),
  (3, 3, '33', 'detector_fumaca', 'Mezanino - Sala Administrativa', 'Detector de Fumaça Pontual', 'csv|3|3|33'),
  (3, 3, '34', 'detector_fumaca', 'Mezanino - Sala Administrativa', 'Detector de Fumaça Pontual', 'csv|3|3|34'),
  (3, 3, '35', 'detector_fumaca', 'Mezanino - Embalagem Manteiga', 'Detector de Fumaça Pontual', 'csv|3|3|35'),
  (3, 3, '36', 'detector_fumaca', 'Mezanino - Embalagem Manteiga', 'Detector de Fumaça Pontual', 'csv|3|3|36'),
  (3, 3, '37', 'detector_fumaca', 'Mezanino - Saída de Paletes', 'Detector de Fumaça Pontual', 'csv|3|3|37'),
  (3, 3, '38', 'detector_fumaca', 'Mezanino - Mixers', 'Detector de Fumaça Pontual', 'csv|3|3|38'),
  (3, 3, '39', 'detector_fumaca', 'Mezanino - Mixers', 'Detector de Fumaça Pontual', 'csv|3|3|39'),
  (3, 3, '40', 'detector_fumaca', 'Mezanino - Mixers', 'Detector de Fumaça Pontual', 'csv|3|3|40'),
  (3, 3, '41', 'detector_fumaca', 'Mezanino - Prensa 3', 'Detector de Fumaça Pontual', 'csv|3|3|41'),
  (3, 3, '42', 'detector_fumaca', 'Mezanino - Prensa 3', 'Detector de Fumaça Pontual', 'csv|3|3|42'),
  (3, 3, '43', 'detector_fumaca', 'Mezanino - Sala de Paineis Pulverização', 'Detector de Fumaça Pontual', 'csv|3|3|43'),
  (3, 3, '44', 'detector_fumaca', 'Mezanino - Pulverização Linha 3', 'Detector de Fumaça Pontual', 'csv|3|3|44'),
  (3, 3, '45', 'detector_fumaca', 'Mezanino - Pulverização Linha 3', 'Detector de Fumaça Pontual', 'csv|3|3|45'),
  (3, 3, '46', 'detector_fumaca', 'Mezanino - Sala de Utilidades', 'Detector de Fumaça Pontual', 'csv|3|3|46'),
  (3, 3, '47', 'detector_fumaca', 'Mezanino - Sala de Utilidades', 'Detector de Fumaça Pontual', 'csv|3|3|47'),
  (3, 3, '48', 'detector_fumaca', 'Mezanino - Pulverização FaII - Nivel 2', 'Detector de Fumaça Pontual', 'csv|3|3|48'),
  (3, 3, '49', 'detector_fumaca', 'Mezanino - Pulverização FaII - Nivel 2', 'Detector de Fumaça Pontual', 'csv|3|3|49'),
  (3, 3, '50', 'detector_fumaca', 'Mezanino - Pulverização Fase II - PV 1', 'Detector de Fumaça Pontual', 'csv|3|3|50'),
  (3, 3, '51', 'detector_fumaca', 'Mezanino - Pulverização Fase II - PV 1', 'Detector de Fumaça Pontual', 'csv|3|3|51'),
  (3, 3, '52', 'detector_fumaca', 'Mezanino - Pulverização Nivel 2', 'Detector de Fumaça Pontual', 'csv|3|3|52'),
  (3, 3, '53', 'detector_fumaca', 'Mezanino - Pulverização PV 1', 'Detector de Fumaça Pontual', 'csv|3|3|53'),
  (3, 3, '54', 'detector_fumaca', 'Mezanino - Pulverização PV 1', 'Detector de Fumaça Pontual', 'csv|3|3|54'),
  (3, 3, '55', 'detector_fumaca', 'Mezanino - Pulverização Linha 3 - Nivel 2', 'Detector de Fumaça Pontual', 'csv|3|3|55'),
  (3, 3, '56', 'detector_fumaca', 'Mezanino - Pulverização Linha 3 - Nivel 2', 'Detector de Fumaça Pontual', 'csv|3|3|56'),
  (3, 3, '57', 'detector_fumaca', 'Mezanino - Pulverização Linha 3 - Nivel 2', 'Detector de Fumaça Pontual', 'csv|3|3|57'),
  (3, 3, '58', 'detector_fumaca', 'Mezanino - Pulverização Linha 3 - Nivel 3', 'Detector de Fumaça Pontual', 'csv|3|3|58'),
  (3, 3, '59', 'detector_fumaca', 'Mezanino - Pulverização Linha 3 - Nivel 3', 'Detector de Fumaça Pontual', 'csv|3|3|59'),
  (3, 3, '60', 'detector_fumaca', 'Mezanino - Torrefação Nivel 2', 'Detector de Fumaça Pontual', 'csv|3|3|60'),
  (3, 3, '61', 'detector_fumaca', 'Mezanino - Torrefação Nivel 2', 'Detector de Fumaça Pontual', 'csv|3|3|61'),
  (3, 3, '62', 'detector_fumaca', 'Mezanino - Torrefação 2 - Nivel 2', 'Detector de Fumaça Pontual', 'csv|3|3|62'),
  (3, 3, '63', 'detector_fumaca', 'Mezanino - Torrefação 2 - Nivel 2', 'Detector de Fumaça Pontual', 'csv|3|3|63'),
  (3, 3, '64', 'detector_fumaca', 'Mezanino - Torrefação 2 - Nivel 3', 'Detector de Fumaça Pontual', 'csv|3|3|64'),
  (3, 3, '65', 'detector_fumaca', 'Mezanino - Torrefação 2- Nivel 4', 'Detector de Fumaça Pontual', 'csv|3|3|65'),
  (3, 3, '66', 'detector_fumaca', 'Mezanino - Linha de Separação -  Nivel 2', 'Detector de Fumaça Pontual', 'csv|3|3|66'),
  (3, 3, '67', 'detector_fumaca', 'Mezanino - Linha de Separação -  Nivel 2', 'Detector de Fumaça Pontual', 'csv|3|3|67'),
  (3, 3, '68', 'detector_fumaca', 'Mezanino - Linha 2 - Nivel 2', 'Detector de Fumaça Pontual', 'csv|3|3|68'),
  (3, 3, '69', 'detector_fumaca', 'Mezanino - Linha 2 - Nivel 3', 'Detector de Fumaça Pontual', 'csv|3|3|69'),
  (3, 3, '70', 'detector_fumaca', 'Mezanino - Mixers - Nivel - 2-3', 'Detector de Fumaça Pontual', 'csv|3|3|70'),
  (3, 3, '71', 'detector_fumaca', 'Mezanino - Mixers - Nivel - 2-3', 'Detector de Fumaça Pontual', 'csv|3|3|71'),
  (4, 1, '1', 'acionador', 'Caldeira', 'Acionador', 'csv|4|1|1'),
  (4, 1, '2', 'acionador', 'Caldeira', 'Acionador', 'csv|4|1|2'),
  (4, 1, '3', 'acionador', 'Caldeira', 'Acionador', 'csv|4|1|3'),
  (4, 1, '4', 'acionador', 'Caldeira', 'Acionador', 'csv|4|1|4'),
  (4, 1, '5', 'acionador', 'Caldeira - 1PV', 'Acionador', 'csv|4|1|5'),
  (4, 1, '6', 'detector_fumaca', 'Caldeira', 'Detector de Fumaça Pontual', 'csv|4|1|6'),
  (4, 1, '7', 'detector_fumaca', 'Caldeira', 'Detector de Fumaça Pontual', 'csv|4|1|7'),
  (4, 1, '8', 'detector_fumaca', 'Caldeira', 'Detector de Fumaça Pontual', 'csv|4|1|8'),
  (4, 1, '9', 'detector_fumaca', 'Caldeira', 'Detector de Fumaça Pontual', 'csv|4|1|9'),
  (4, 1, '10', 'detector_fumaca', 'Caldeira', 'Detector de Fumaça Pontual', 'csv|4|1|10'),
  (4, 1, '11', 'detector_fumaca', 'Caldeira', 'Detector de Fumaça Pontual', 'csv|4|1|11'),
  (4, 1, '12', 'detector_fumaca', 'Caldeira', 'Detector de Fumaça Pontual', 'csv|4|1|12'),
  (4, 1, '13', 'detector_fumaca', 'Caldeira', 'Detector de Fumaça Pontual', 'csv|4|1|13'),
  (4, 1, '14', 'detector_fumaca', 'Caldeira', 'Detector de Fumaça Pontual', 'csv|4|1|14'),
  (4, 1, '15', 'detector_fumaca', 'Caldeira', 'Detector de Fumaça Pontual', 'csv|4|1|15'),
  (4, 1, '16', 'detector_fumaca', 'Caldeira', 'Detector de Fumaça Pontual', 'csv|4|1|16'),
  (4, 1, '17', 'detector_fumaca', 'Caldeira', 'Detector de Fumaça Pontual', 'csv|4|1|17'),
  (4, 1, '18', 'detector_fumaca', 'Caldeira', 'Detector de Fumaça Pontual', 'csv|4|1|18'),
  (4, 1, '19', 'detector_fumaca', 'Caldeira - 1PV', 'Detector de Fumaça Pontual', 'csv|4|1|19'),
  (4, 1, '20', 'detector_fumaca', 'Caldeira - 1PV', 'Detector de Fumaça Pontual', 'csv|4|1|20'),
  (4, 1, '21', 'detector_fumaca', 'Caldeira - 1PV', 'Detector de Fumaça Pontual', 'csv|4|1|21'),
  (4, 1, '22', 'detector_fumaca', 'Caldeira - Nivel 2', 'Detector de Fumaça Pontual', 'csv|4|1|22'),
  (4, 1, '93', 'sirene', 'Caldeira', 'Sirenes', 'csv|4|1|93'),
  (4, 1, '94', 'sirene', 'Caldeira', 'Sirenes', 'csv|4|1|94'),
  (4, 1, '95', 'sirene', 'Caldeira', 'Sirenes', 'csv|4|1|95'),
  (4, 1, '96', 'sirene', 'Caldeira', 'Sirenes', 'csv|4|1|96'),
  (4, 1, '97', 'sirene', 'Caldeira - 1PV', 'Sirenes', 'csv|4|1|97')
) AS v(central_num, laco, endereco, tipo, setor, descricao, seed_key)
JOIN centrais c ON c.numero = v.central_num
ON CONFLICT (seed_key) DO UPDATE SET
  laco             = EXCLUDED.laco,
  endereco         = EXCLUDED.endereco,
  tipo_dispositivo = EXCLUDED.tipo_dispositivo,
  setor            = EXCLUDED.setor,
  descricao        = EXCLUDED.descricao,
  cadastro_pendente = false;
  -- status_instalacao / fotos / observações deliberately NOT overwritten.
